// Generated by scripts/build-v12-executor.mjs. Do not edit directly.
//#region services/v12-executor/entry-policy.ts
var OrderHttpError = class extends Error {
	status;
	body;
	constructor(status, body) {
		super(`Kalshi order POST failed: ${status} ${JSON.stringify(body)}`);
		this.name = "OrderHttpError";
		this.status = status;
		this.body = body;
	}
};
function isPostOnlyCrossRejection(error) {
	if (!(error instanceof OrderHttpError) || error.status !== 400) return false;
	const e = error.body?.error;
	return !error.body?.order_id && !error.body?.order?.order_id && e?.code === "invalid_order" && typeof e.details === "string" && e.details.trim().toLowerCase() === "post only cross";
}
function policyFromEnv(get) {
	const num = (key, fallback) => {
		const text = get(key);
		const value = text === void 0 ? fallback : Number(text);
		if (!Number.isFinite(value)) throw new Error(`Invalid ${key}`);
		return value;
	};
	const mode = get("ENTRY_POLICY_MODE") ?? "disabled";
	if (![
		"disabled",
		"shadow",
		"live"
	].includes(mode)) throw new Error("Invalid ENTRY_POLICY_MODE");
	const p = {
		version: "entry-controls-r1",
		mode,
		minOdds: num("ENTRY_MIN_ODDS", num("RETRY_MIN_ODDS", 1.5)),
		feeReserve: num("ENTRY_FEE_RESERVE_PER_CONTRACT", .03),
		slippage: num("ENTRY_MAX_SLIPPAGE_CENTS", 1) / 100,
		makerImprovement: num("ENTRY_MAKER_IMPROVEMENT_CENTS", 1) / 100,
		makerWaitMs: num("ENTRY_MAKER_WAIT_MS", 1500),
		makerEnabled: get("ENTRY_MAKER_ENABLED") === "true",
		maxEntryAgeMs: num("ENTRY_MAX_AGE_MS", 6e4),
		quoteMaxAgeMs: num("ENTRY_QUOTE_MAX_AGE_MS", 1e3),
		pollMs: num("ENTRY_BOOK_POLL_MS", 300)
	};
	if (p.minOdds <= 1 || p.feeReserve < 0 || p.feeReserve >= .25 || p.slippage < 0 || p.slippage > .05 || p.makerImprovement < .01 || p.makerImprovement > .1 || p.makerWaitMs < 0 || p.makerWaitMs > 5e3 || p.maxEntryAgeMs < 1e3 || p.maxEntryAgeMs > 12e4 || p.quoteMaxAgeMs < 100 || p.quoteMaxAgeMs > 5e3 || p.pollMs < 200) throw new Error("Entry policy outside supported bounds");
	return p;
}
function readBook(raw, side, started, received) {
	const book = raw?.orderbook_fp;
	if (!book) throw new Error("ORDERBOOK_SCHEMA_UNAVAILABLE");
	const levels = (key) => {
		const data = book[key];
		if (!Array.isArray(data)) throw new Error("ORDERBOOK_SCHEMA_UNAVAILABLE");
		return data.map((x) => [Number(x[0]), Number(x[1])]).filter((x) => x.every(Number.isFinite) && x[0] > 0 && x[0] < 1 && x[1] > 0).sort((a, b) => b[0] - a[0]);
	};
	const same = levels(side === "yes" ? "yes_dollars" : "no_dollars");
	const other = levels(side === "yes" ? "no_dollars" : "yes_dollars");
	if (!same.length || !other.length) throw new Error("EMPTY_ORDERBOOK");
	const q = {
		bid: same[0][0],
		ask: Number((1 - other[0][0]).toFixed(4)),
		askSize: other[0][1],
		observedAt: received,
		requestStartedAt: started,
		source: "kalshi_direct_orderbook"
	};
	if (q.bid >= q.ask) throw new Error("CROSSED_OR_LOCKED_ORDERBOOK");
	return q;
}
function validateMarket(m, ticker, target, now) {
	if (!/^KXBTC15M-/.test(ticker) || m?.ticker !== ticker || m.market_type !== "binary") throw new Error("MARKET_IDENTITY_MISMATCH");
	const close = Date.parse(m.close_time);
	const open = Date.parse(m.open_time);
	if (close !== target + 9e5 || !Number.isFinite(open) || open > now || now >= close) throw new Error("MARKET_WINDOW_MISMATCH");
	if (!["active", "open"].includes(m.status)) throw new Error("MARKET_NOT_ACTIVE");
	if (m.result === "yes" || m.result === "no") throw new Error("MARKET_ALREADY_RESOLVED");
}
var downCent = (x) => Math.floor((x + 1e-10) * 100) / 100;
function firstCeiling(q, p) {
	return downCent(Math.min(.99, 1 / p.minOdds - (p.admissionFeeReserve ?? p.feeReserve), q.ask + p.slippage));
}
function planOrder(q, p, kind, budget, ceiling, remaining, now) {
	if (now < q.observedAt || now - q.requestStartedAt > p.quoteMaxAgeMs) throw new Error("STALE_ORDERBOOK");
	if (p.valueLimit !== void 0) {
		if (!Number.isFinite(p.valueLimit) || !Number.isFinite(p.knownAsk)) throw new Error("INVALID_U_VALUE_LIMIT");
		const conservative = Math.max(p.knownAsk, q.ask) + .01;
		if (conservative >= 1 || conservative + .07 * conservative * (1 - conservative) > p.valueLimit + 1e-12) return null;
	}
	const limit = downCent(Math.min(ceiling, kind === "maker" ? q.ask - p.makerImprovement : q.ask + p.slippage));
	if (limit < .01 || kind === "taker" && q.ask > limit + 1e-9) return null;
	const affordable = Math.floor((budget + 1e-9) / (limit + p.feeReserve) * 100) / 100;
	const count = Math.floor(Math.min(remaining, affordable, kind === "taker" ? q.askSize : Infinity) * 100 + 1e-8) / 100;
	if (count < .01 || limit + p.feeReserve > 1 / p.minOdds + 1e-9) return null;
	return {
		kind,
		limit,
		count,
		maxCost: count * (limit + p.feeReserve),
		minimumOdds: 1 / (limit + p.feeReserve),
		quote: q
	};
}
function orderBody(ticker, side, plan, clientId, now, p, entryDeadline = Infinity) {
	return {
		ticker,
		client_order_id: clientId,
		side: side === "yes" ? "bid" : "ask",
		count: plan.count.toFixed(2),
		price: (side === "yes" ? plan.limit : 1 - plan.limit).toFixed(4),
		time_in_force: plan.kind === "maker" ? "good_till_canceled" : "immediate_or_cancel",
		post_only: plan.kind === "maker",
		self_trade_prevention_type: "taker_at_cross",
		cancel_order_on_pause: true,
		...plan.kind === "maker" ? { expiration_time: Math.min(Math.ceil((now + p.makerWaitMs) / 1e3), Math.floor(entryDeadline / 1e3)) } : {}
	};
}
function orderState(raw, requested) {
	const o = raw?.order ?? raw;
	const fill = Number(o?.fill_count_fp ?? o?.fill_count);
	const remaining = Number(o?.remaining_count_fp ?? o?.remaining_count);
	if (!Number.isFinite(fill) || fill < 0 || fill > requested + 1e-6 || !Number.isFinite(remaining) || remaining < 0) throw new Error("INVALID_ORDER_STATE");
	const terminal = [
		"executed",
		"canceled",
		"cancelled"
	].includes(o.status) && remaining === 0;
	const keys = [
		"maker_fill_cost_dollars",
		"taker_fill_cost_dollars",
		"maker_fees_dollars",
		"taker_fees_dollars"
	];
	const hasCost = keys.every((k) => o[k] !== void 0 && Number.isFinite(Number(o[k])) && Number(o[k]) >= 0);
	return {
		fill,
		remaining,
		terminal,
		status: o.status,
		actualCost: hasCost ? keys.reduce((sum, k) => sum + Number(o[k]), 0) : null,
		fees: hasCost ? Number(o.maker_fees_dollars) + Number(o.taker_fees_dollars) : null
	};
}
//#endregion
//#region services/v12-executor/entry-engine.ts
async function executeEntry(d, p, input) {
	const trace = {
		policy: p,
		revision: "cancel-confirmation-r1",
		target: input.target,
		received_at: input.received,
		status: "STARTING",
		events: []
	};
	const attempts = [];
	let row = null;
	let submitted = false;
	let writeReserveMs = 100;
	const event = (type, data = {}) => trace.events.push({
		type,
		at: d.now(),
		...data
	});
	const save = async (patch = {}) => {
		if (row) {
			const started = d.now();
			await d.save(row, {
				execution_trace: structuredClone(trace),
				order_attempts: structuredClone(attempts),
				...patch
			});
			event("durable_save_complete", {
				elapsed_ms: d.now() - started,
				attempts: attempts.length
			});
		}
	};
	const allowed = () => {
		if (d.now() < input.target || d.now() - input.target > p.maxEntryAgeMs) throw new Error("ENTRY_DEADLINE");
	};
	const readyTask = async () => {
		const q = await d.ready();
		event("market_ready", { quote: q });
		return q;
	};
	if (p.mode === "disabled") {
		trace.status = "DISABLED";
		d.log(trace);
		return trace;
	}
	if (!["maker_only", "taker_only"].includes(p.executionRoute ?? "")) throw new Error("V12_EXECUTION_ROUTE_REQUIRED");
	const ready = readyTask();
	ready.catch(() => {});
	try {
		const preflight = d.preflight();
		preflight.catch(() => {});
		if (p.mode === "live") {
			const started = d.now();
			row = await d.claim();
			trace.bet_id = row;
			const elapsed = d.now() - started;
			writeReserveMs = Math.max(100, Math.min(p.quoteMaxAgeMs, elapsed + 50));
			event("claim_complete", {
				claimed: !!row,
				elapsed_ms: elapsed,
				write_reserve_ms: writeReserveMs
			});
			if (!row) {
				trace.status = "CLAIM_REJECTED";
				d.log(trace);
				return trace;
			}
		}
		const checks = await preflight;
		event("preflight_complete", checks);
		if (checks.paused || checks.stopped || !Number.isFinite(checks.budget) || checks.budget <= 0) {
			trace.status = "PREFLIGHT_BLOCKED";
			await save({ result: "cancelled" });
			d.log(trace);
			return trace;
		}
		let q = await ready;
		allowed();
		if (d.now() - q.requestStartedAt > p.quoteMaxAgeMs) q = await d.quote();
		const ceiling = firstCeiling(q, p);
		const desired = Math.floor(checks.budget / (ceiling + p.feeReserve));
		trace.initial_ceiling = ceiling;
		trace.budget = checks.budget;
		trace.desired_count = desired;
		let remaining = desired;
		let budget = checks.budget;
		let totalFill = 0;
		let spent = 0;
		let actualKnown = true;
		let fees = 0;
		const kinds = p.executionRoute === "maker_only" ? ["maker"] : ["taker"];
		if (p.mode === "shadow") {
			trace.status = "SHADOW_PLAN";
			trace.plans = kinds.map((k) => planOrder(q, p, k, budget, ceiling, remaining, d.now()));
			d.log(trace);
			return trace;
		}
		for (const kind of kinds) {
			allowed();
			if (attempts.length) {
				const again = await d.preflight();
				if (again.paused || again.stopped) {
					event("fallback_preflight_blocked");
					break;
				}
				q = await d.quote();
			}
			let plan = planOrder(q, p, kind, budget, ceiling, remaining, d.now());
			if (!plan) {
				event("price_or_size_abstention", {
					kind,
					quote: q
				});
				continue;
			}
			if (!attempts.length && d.now() - q.requestStartedAt + writeReserveMs > p.quoteMaxAgeMs) {
				event("refresh_before_intent", {
					quote_age_ms: d.now() - q.requestStartedAt,
					write_reserve_ms: writeReserveMs
				});
				q = await d.quote();
				allowed();
				const fresh = planOrder(q, p, kind, budget, ceiling, Math.min(remaining, plan.count), d.now());
				if (!fresh) {
					event("pre_intent_price_or_size_abstention", {
						kind,
						quote: q
					});
					break;
				}
				plan = fresh;
			}
			const clientId = d.id();
			const a = {
				kind,
				client_order_id: clientId,
				plan,
				state: "INTENT",
				created_at: d.now()
			};
			attempts.push(a);
			event("order_intent", {
				kind,
				client_order_id: clientId
			});
			await save({
				market: input.ticker,
				bet_size: checks.budget
			});
			allowed();
			if (d.now() - q.requestStartedAt > p.quoteMaxAgeMs) {
				event("stale_after_save", { refresh_attempt: 1 });
				q = await d.quote();
				allowed();
				const refreshed = planOrder(q, p, kind, budget, ceiling, Math.min(remaining, plan.count), d.now());
				if (!refreshed) {
					a.state = "NOT_SUBMITTED_PRICE_OR_SIZE";
					event("refresh_price_or_size_abstention", {
						kind,
						quote: q
					});
					await save();
					break;
				}
				plan = refreshed;
				a.plan = plan;
				a.replanned_at = d.now();
				event("intent_refreshed", {
					kind,
					quote: q,
					limit: plan.limit,
					count: plan.count
				});
				await save();
				allowed();
				if (d.now() - q.requestStartedAt > p.quoteMaxAgeMs) {
					a.state = "NOT_SUBMITTED_STALE";
					event("refresh_stale_after_save");
					await save();
					break;
				}
			}
			if (d.beforeSubmit) await d.beforeSubmit();
			allowed();
			if (d.now() - q.requestStartedAt > p.quoteMaxAgeMs) throw new Error("PRE_SUBMIT_EXPIRED");
			a.submit_started_at = d.now();
			const previouslySubmitted = submitted;
			submitted = true;
			let raw;
			try {
				raw = await d.submit(orderBody(input.ticker, input.side, plan, clientId, d.now(), p, input.target + p.maxEntryAgeMs));
			} catch (error) {
				a.response_received_at = d.now();
				if (kind !== "maker" || !isPostOnlyCrossRejection(error)) throw error;
				submitted = previouslySubmitted;
				a.state = "REJECTED";
				a.rejection = {
					http_status: error.status,
					code: error.body.error.code,
					details: error.body.error.details
				};
				event("order_rejected", {
					kind,
					...a.rejection,
					elapsed_ms: a.response_received_at - a.submit_started_at
				});
				await save();
				continue;
			}
			const order = raw?.order ?? raw;
			a.response_received_at = d.now();
			a.order_id = order?.order_id;
			if (!a.order_id) throw new Error("ORDER_RESPONSE_MISSING_ID");
			a.state = "ACCEPTED";
			event("order_response", {
				kind,
				order_id: a.order_id,
				elapsed_ms: a.response_received_at - a.submit_started_at
			});
			await save({
				order_id: a.order_id,
				...kind === "maker" ? { maker_order_id: a.order_id } : {},
				placed_at: new Date(a.response_received_at).toISOString(),
				seconds_after_open: Math.round((a.response_received_at - input.target) / 1e3)
			});
			if (kind === "maker") await d.sleep(Math.max(0, a.submit_started_at + p.makerWaitMs - d.now()));
			let state = orderState(await d.read(a.order_id), plan.count);
			if (!state.terminal) {
				a.observation = state;
				const cancelStarted = d.now();
				const confirmationDeadline = Math.min(cancelStarted + 2e3, input.target + p.maxEntryAgeMs);
				let confirmationBlocked = false;
				event("cancel_requested", {
					order_id: a.order_id,
					status: state.status,
					fill: state.fill,
					remaining: state.remaining,
					confirmation_deadline: confirmationDeadline
				});
				try {
					const timeout = confirmationDeadline > d.now() ? confirmationDeadline - d.now() : 2e3;
					const rawCancel = await d.cancel(a.order_id, AbortSignal.timeout(Math.ceil(timeout)));
					const cancel = rawCancel?.order ?? rawCancel;
					event("cancel_response", {
						order_id: a.order_id,
						elapsed_ms: d.now() - cancelStarted,
						response_order_id: cancel?.order_id ?? null,
						reduced_by: cancel?.reduced_by ?? null,
						venue_ts_ms: cancel?.ts_ms ?? null
					});
				} catch (e) {
					const httpStatus = e?.status;
					confirmationBlocked = httpStatus === 418 || httpStatus === 429;
					event("cancel_error", {
						order_id: a.order_id,
						elapsed_ms: d.now() - cancelStarted,
						http_status: httpStatus ?? null,
						error: String(e)
					});
				}
				for (let check = 1; !confirmationBlocked && check <= 8 && d.now() < confirmationDeadline; check++) {
					const checkStarted = d.now();
					try {
						const signal = AbortSignal.timeout(Math.max(1, Math.ceil(confirmationDeadline - checkStarted)));
						state = orderState(await d.read(a.order_id, signal), plan.count);
						a.observation = state;
						event("cancel_confirmation", {
							order_id: a.order_id,
							check,
							request_started_at: checkStarted,
							elapsed_ms: d.now() - checkStarted,
							status: state.status,
							fill: state.fill,
							remaining: state.remaining,
							terminal: state.terminal
						});
						if (state.terminal) break;
					} catch (e) {
						const httpStatus = e?.status;
						event("cancel_confirmation_error", {
							order_id: a.order_id,
							check,
							request_started_at: checkStarted,
							elapsed_ms: d.now() - checkStarted,
							http_status: httpStatus ?? null,
							error: String(e)
						});
						if (httpStatus >= 400 && httpStatus < 500 || ["AbortError", "TimeoutError"].includes(e?.name)) break;
					}
					const left = confirmationDeadline - d.now();
					if (check < 8 && left > 0) await d.sleep(Math.min(250, left));
				}
				if (!state.terminal) event("cancel_confirmation_unresolved", {
					order_id: a.order_id,
					elapsed_ms: d.now() - cancelStarted,
					deadline_reached: d.now() >= confirmationDeadline
				});
			}
			if (!state.terminal) {
				a.state = "UNRESOLVED";
				a.observation = state;
				throw new Error("ORDER_NOT_TERMINAL");
			}
			a.state = "TERMINAL";
			a.observation = state;
			a.reconciled_at = d.now();
			totalFill += state.fill;
			remaining = Math.max(0, desired - totalFill);
			const reservedCost = state.fill * (plan.limit + p.feeReserve);
			if (state.actualCost !== null && state.actualCost > reservedCost + 1e-4) throw new Error("FEE_OR_PRICE_RESERVE_EXCEEDED");
			const cost = state.actualCost ?? reservedCost;
			actualKnown = actualKnown && state.actualCost !== null;
			spent += cost;
			fees += state.fees ?? 0;
			budget = Math.max(0, checks.budget - spent);
			event("order_terminal", {
				kind,
				...state,
				remaining,
				remaining_budget: budget
			});
			await save({
				contracts: totalFill,
				...actualKnown ? {
					total_cost: Number(spent.toFixed(2)),
					fee: Number(fees.toFixed(4)),
					fill_price: totalFill ? Number((spent / totalFill).toFixed(4)) : 0,
					odds: spent ? Number((totalFill / spent).toFixed(2)) : 0
				} : {},
				...totalFill ? {
					filled_at: new Date(d.now()).toISOString(),
					fill_confirmed_by: "poll"
				} : {}
			});
			if (remaining < .01) break;
			if (d.now() >= input.target + p.maxEntryAgeMs) {
				event("fallback_deadline_reached");
				break;
			}
		}
		trace.status = totalFill > 0 ? "FILLED" : attempts.some((a) => a.order_id) ? "NO_FILL" : attempts.some((a) => a.state === "REJECTED") ? "REJECTED_NO_FILL" : attempts.some((a) => String(a.state).startsWith("NOT_SUBMITTED")) ? "NOT_SUBMITTED" : "NO_FILL";
		trace.filled_count = totalFill;
		trace.cost_is_actual = actualKnown;
		trace.cost_or_reserved_cost = spent;
		await save({ result: totalFill > 0 ? "pending" : "cancelled" });
	} catch (e) {
		trace.status = submitted ? "RECONCILIATION_REQUIRED" : "NOT_SUBMITTED";
		event("error", { message: String(e) });
		try {
			await save(submitted ? {} : { result: "cancelled" });
		} catch (saveError) {
			event("save_error", { message: String(saveError) });
		}
	}
	d.log(trace);
	return trace;
}
//#endregion
//#region src/lib/v12/contract.ts
/** Frozen V1.2 request. This module cannot place or dispatch an order. */
var V12_VERSION = "v12-original-u-4-5-10-r1";
var ROUTES = {
	V1: {
		model: "v12-v1-r1",
		fraction: .04,
		percent: 4,
		execution: "maker_only",
		endpoint: "v12-v1"
	},
	T45R2: {
		model: "v12-t45r2-r1",
		fraction: .05,
		percent: 5,
		execution: "taker_only",
		endpoint: "v12-t45r2"
	},
	U: {
		model: "v12-original-u-r1",
		fraction: .1,
		percent: 10,
		execution: "maker_only",
		endpoint: "v12-u"
	}
};
function boiseDay(now) {
	if (!Number.isFinite(now.getTime())) throw new Error("INVALID_TIME");
	const parts = new Intl.DateTimeFormat("en-US", {
		timeZone: "America/Boise",
		year: "numeric",
		month: "2-digit",
		day: "2-digit"
	}).formatToParts(now);
	const get = (key) => parts.find((p) => p.type === key).value;
	return `${get("year")}-${get("month")}-${get("day")}`;
}
//#endregion
//#region services/v12-executor/route-policy.ts
function routePolicy(base, signal, nowMs) {
	const route = signal.leg, locked = ROUTES[route], open = Date.parse(signal.candle_starts_at), decision = Date.parse(signal.decision_at);
	if (!locked || signal.model_version !== locked.model || signal.execution_policy !== locked.execution || !Number.isFinite(open) || !Number.isFinite(decision) || decision < open || nowMs < decision || nowMs - decision > 1e4) throw new Error("INVALID_V12_EXECUTION_IDENTITY");
	const maker = locked.execution === "maker_only";
	if (route === "U") {
		if (![
			120,
			180,
			300,
			480,
			600,
			720
		].includes(signal.checkpoint_seconds) || decision < open + signal.checkpoint_seconds * 1e3 || decision > open + signal.checkpoint_seconds * 1e3 + 5e3 || !Number.isFinite(signal.limit_all_in) || signal.limit_all_in <= 0 || signal.limit_all_in >= 1 || !Number.isFinite(signal.known_ask) || signal.known_ask <= 0 || signal.known_ask >= 1) throw new Error("INVALID_U_CHECKPOINT");
	} else if (decision - open > 6e4 || route === "T45R2" && decision - open < 45e3) throw new Error("INVALID_EARLY_WINDOW");
	return {
		...base,
		version: "entry-controls-r1",
		strategyVersion: "v12-original-u-4-5-10-r1",
		executionRoute: locked.execution,
		makerEnabled: maker,
		feeReserve: maker ? 0 : base.feeReserve,
		admissionFeeReserve: route === "U" ? 0 : base.feeReserve,
		minOdds: route === "U" ? 1 / signal.limit_all_in : route === "T45R2" ? 1.4 : 1.5,
		maxEntryAgeMs: route === "U" ? signal.checkpoint_seconds * 1e3 + 5e3 : 6e4,
		...route === "U" ? {
			valueLimit: signal.limit_all_in,
			knownAsk: signal.known_ask
		} : {}
	};
}
//#endregion
//#region services/v12-executor/market-source.ts
function marketSource(get, now, sleep, ticker, target, side, p, log) {
	const quote = async () => {
		const started = now();
		return readBook(await get(`/trade-api/v2/markets/${encodeURIComponent(ticker)}/orderbook`), side, started, now());
	};
	const ready = async () => {
		let lastError = "NO_MARKET";
		let polls = 0;
		while (now() - target <= p.maxEntryAgeMs) {
			polls++;
			const started = now();
			try {
				const [meta, q] = await Promise.all([get(`/trade-api/v2/markets/${encodeURIComponent(ticker)}`), quote()]);
				validateMarket(meta?.market ?? meta, ticker, target, now());
				if (now() - q.requestStartedAt > p.quoteMaxAgeMs) throw new Error("STALE_ORDERBOOK");
				log({
					type: "market_source_ready",
					polls,
					at: now(),
					elapsed_ms: now() - started
				});
				return q;
			} catch (e) {
				lastError = String(e);
				if (e?.retryAfterMs || /IDENTITY_MISMATCH|WINDOW_MISMATCH|ALREADY_RESOLVED/.test(lastError)) throw e;
				if (polls === 1 || polls % 10 === 0) log({
					type: "market_source_wait",
					polls,
					at: now(),
					error: lastError
				});
				await sleep(p.pollMs);
			}
		}
		throw new Error(`ENTRY_DEADLINE:${lastError}`);
	};
	return {
		quote,
		ready
	};
}
//#endregion
//#region services/v12-executor/live.ts
var EXECUTOR_REVISION = "v12-executor-r1";
var enc = new TextEncoder();
var sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
function dayStart(day) {
	const midnight = Date.parse(day + "T00:00:00Z");
	let candidate = midnight;
	for (let i = 0; i < 3; i++) {
		const m = new Intl.DateTimeFormat("en-US", {
			timeZone: "America/Boise",
			timeZoneName: "longOffset"
		}).formatToParts(candidate).find((p) => p.type === "timeZoneName").value.match(/GMT([+-])(\d{2}):(\d{2})/);
		if (!m) throw Error("TIMEZONE_OFFSET_UNAVAILABLE");
		candidate = midnight - (m[1] === "-" ? -1 : 1) * (Number(m[2]) * 60 + Number(m[3])) * 6e4;
	}
	return candidate;
}
function client(get, transport, clock) {
	const base = get("SUPABASE_URL"), key = get("SUPABASE_SERVICE_ROLE_KEY") || get("KALSHI_SUPABASE_SERVICE_ROLE");
	if (!base || !key) throw Error("STORAGE_NOT_CONFIGURED");
	const headers = {
		apikey: key,
		Authorization: "Bearer " + key,
		"content-type": "application/json"
	};
	const db = async (path, method = "GET", body) => {
		const r = await transport(base + "/rest/v1/" + path, {
			method,
			headers: {
				...headers,
				Prefer: "return=representation"
			},
			...body === void 0 ? {} : { body: JSON.stringify(body) },
			signal: AbortSignal.timeout(4e3)
		});
		if (!r.ok) {
			if (method === "POST" && r.status === 409) return null;
			throw Error("V12_STORAGE_HTTP_" + r.status);
		}
		return r.status === 204 ? null : r.json();
	};
	let privateKey;
	const host = get("KALSHI_BASE_URL") || "https://api.elections.kalshi.com";
	if (!["https://api.elections.kalshi.com", "https://external-api.kalshi.com"].includes(host)) throw Error("UNEXPECTED_EXCHANGE_HOST");
	const exchange = async (method, path, body, params, signal) => {
		if (!privateKey) {
			const pem = (get("KALSHI_PRIVATE_KEY_PEM") || "").replace(/\\n/g, "\n").replace(/-----[A-Z ]+-----/g, "").replace(/\s/g, "");
			privateKey = await crypto.subtle.importKey("pkcs8", Uint8Array.from(atob(pem), (c) => c.charCodeAt(0)), {
				name: "RSA-PSS",
				hash: "SHA-256"
			}, false, ["sign"]);
		}
		const ts = String(clock()), sig = await crypto.subtle.sign({
			name: "RSA-PSS",
			saltLength: 32
		}, privateKey, enc.encode(ts + method + path));
		const url = new URL(host + path);
		for (const [k, v] of Object.entries(params || {})) url.searchParams.set(k, v);
		const r = await transport(url.toString(), {
			method,
			headers: {
				"content-type": "application/json",
				"KALSHI-ACCESS-KEY": get("KALSHI_KEY_ID") || "",
				"KALSHI-ACCESS-TIMESTAMP": ts,
				"KALSHI-ACCESS-SIGNATURE": btoa(String.fromCharCode(...new Uint8Array(sig)))
			},
			...body === void 0 ? {} : { body: JSON.stringify(body) },
			signal: signal || AbortSignal.timeout(4e3)
		});
		if (!r.ok) {
			if (method === "POST") {
				let detail = {};
				try {
					detail = await r.json();
				} catch {}
				throw new OrderHttpError(r.status, detail);
			}
			throw Object.assign(Error("V12_EXCHANGE_HTTP_" + r.status), { status: r.status });
		}
		return r.json();
	};
	const release = async () => {
		const rows = await db("v12_release_config?version=eq." + V12_VERSION + "&select=mode,live_enabled_at");
		if (rows?.length !== 1 || !["shadow", "live"].includes(rows[0].mode)) throw Error("RELEASE_CONFIG_UNAVAILABLE");
		return rows[0];
	};
	const pause = async () => {
		const rows = await db("bot_config?id=eq.1&select=paused");
		if (rows?.length !== 1 || typeof rows[0].paused !== "boolean") throw Error("PAUSE_STATE_UNAVAILABLE");
		return rows[0].paused;
	};
	return {
		db,
		exchange,
		release,
		pause,
		host
	};
}
async function executionReadiness(get, transport = fetch, clock = Date.now) {
	const c = client(get, transport, clock), day = boiseDay(new Date(clock()));
	const [release, paused, balances] = await Promise.all([
		c.release(),
		c.pause(),
		c.db("daily_balance?date=eq." + day + "&select=balance_at_midnight")
	]);
	const checks = {
		release_config: true,
		daily_opening: balances?.length === 1 && Number(balances[0].balance_at_midnight) > 0,
		bot_unpaused: paused === false,
		exchange_credentials: !!get("KALSHI_KEY_ID") && !!get("KALSHI_PRIVATE_KEY_PEM"),
		exchange_authenticated: false,
		policy_valid: false
	};
	try {
		policyFromEnv((k) => k === "ENTRY_POLICY_MODE" ? "live" : get(k));
		checks.policy_valid = true;
	} catch {}
	if (checks.exchange_credentials) try {
		const cash = await c.exchange("GET", "/trade-api/v2/portfolio/balance");
		checks.exchange_authenticated = Number.isFinite(cash.balance) && cash.balance >= 0;
	} catch {}
	return {
		revision: EXECUTOR_REVISION,
		mode: release.mode,
		ready_for_activation: Object.values(checks).every(Boolean),
		checks,
		records_created: 0,
		orders_submitted: 0,
		execution_enabled: false
	};
}
async function executeV12(signal, receipt, get, transport = fetch, clock = Date.now) {
	if (receipt.status !== "LIVE_ACCEPTED" || receipt.mode !== "live" || receipt.execution_enabled !== true || !receipt.id || !Number.isSafeInteger(receipt.budget_cents) || receipt.budget_cents <= 0) throw Error("LIVE_RECEIPT_REQUIRED");
	const c = client(get, transport, clock), target = Date.parse(signal.candle_starts_at), side = signal.prediction === "YES" ? "yes" : "no", ticker = signal.market;
	const route = signal.leg, received = clock(), day = boiseDay(new Date(received));
	if (receipt.boise_day !== day) throw Error("DAY_OPENING_EXPIRED");
	const policy = routePolicy(policyFromEnv((k) => k === "ENTRY_POLICY_MODE" ? "live" : get(k)), signal, received);
	const maxDollars = Number(get("BET_SIZE_MAX_DOLLARS") || 0);
	if (!Number.isFinite(maxDollars) || maxDollars < 0) throw Error("INVALID_BUDGET_CAP");
	const baseBudget = Math.min(receipt.budget_cents / 100, maxDollars > 0 ? maxDollars : Infinity);
	const stopPct = Number(get("DAILY_STOP_LOSS_PCT") || 0);
	if (!Number.isFinite(stopPct) || stopPct < 0) throw Error("INVALID_STOP_LOSS");
	const activation = async () => {
		const [release, paused] = await Promise.all([c.release(), c.pause()]);
		if (release.mode !== "live" || !release.live_enabled_at || Date.parse(signal.decision_at) < Date.parse(release.live_enabled_at) || boiseDay(new Date(clock())) !== day) throw Error("V12_LIVE_NOT_AUTHORIZED");
		return paused;
	};
	const stopped = async () => {
		if (stopPct === 0) return false;
		const rows = await c.db("bet_history?placed_at=gte." + encodeURIComponent(new Date(dayStart(day)).toISOString()) + "&result=in.(won,lost)&select=result,contracts,total_cost");
		if (!Array.isArray(rows)) throw Error("STOP_LOSS_UNAVAILABLE");
		const net = rows.reduce((s, b) => s + (b.result === "won" ? Number(b.contracts) : 0) - Number(b.total_cost), 0);
		if (!Number.isFinite(net) || !(Number(receipt.opening_balance) > 0)) throw Error("STOP_LOSS_UNAVAILABLE");
		return net <= -stopPct * Number(receipt.opening_balance);
	};
	const publicGet = async (path) => {
		const r = await transport(c.host + path, {
			signal: AbortSignal.timeout(2500),
			cache: "no-store"
		});
		if (!r.ok) throw Object.assign(Error("MARKET_HTTP_" + r.status), { retryAfterMs: [418, 429].includes(r.status) ? 3e4 : void 0 });
		return r.json();
	};
	const log = (data) => console.log(JSON.stringify({
		type: "v12_execution",
		revision: EXECUTOR_REVISION,
		receipt_id: receipt.id,
		leg: route,
		data
	}));
	const source = marketSource(publicGet, clock, sleep, ticker, target, side, policy, log);
	let quote;
	const sizing = {
		policy_version: V12_VERSION,
		model_version: signal.model_version,
		fraction: ROUTES[route].fraction,
		balance_date: day,
		opening_balance: receipt.opening_balance,
		budget_dollars: baseBudget
	};
	const trace = await executeEntry({
		now: clock,
		sleep,
		id: () => crypto.randomUUID(),
		ready: async () => quote = await source.ready(),
		quote: async () => quote = await source.quote(),
		claim: async () => {
			return (await c.db("bet_history", "POST", {
				placed_at: new Date(clock()).toISOString(),
				candle_starts_at: signal.candle_starts_at,
				market: ticker,
				side,
				prediction: signal.prediction,
				confidence: signal.probability || 0,
				contracts: 0,
				fill_price: 0,
				odds: 0,
				fee: 0,
				total_cost: 0,
				bet_size: 0,
				result: "pending",
				order_id: null,
				maker_order_id: null,
				fill_type: null,
				model_version: signal.model_version,
				sent_at: signal.sent_at,
				webhook_received_at: new Date(received).toISOString(),
				seconds_after_open: Math.round((clock() - target) / 1e3),
				execution_trace: {
					policy,
					policy_version: "entry-controls-r1",
					execution_revision: "v12-executor-r1",
					receipt_id: receipt.id,
					sizing,
					status: "CLAIMED"
				},
				order_attempts: []
			}))?.[0]?.id || null;
		},
		preflight: async () => {
			const [paused, stop, cash] = await Promise.all([
				activation(),
				stopped(),
				c.exchange("GET", "/trade-api/v2/portfolio/balance")
			]);
			if (!Number.isSafeInteger(cash.balance) || cash.balance < 0) throw Error("AVAILABLE_CASH_UNAVAILABLE");
			return {
				paused,
				stopped: stop,
				budget: Math.min(baseBudget, cash.balance / 100)
			};
		},
		save: async (id, patch) => {
			const rows = await c.db("bet_history?id=eq." + id + "&select=id", "PATCH", {
				...patch,
				execution_trace: {
					...patch.execution_trace,
					policy_version: "entry-controls-r1",
					execution_revision: EXECUTOR_REVISION,
					receipt_id: receipt.id,
					sizing
				}
			});
			if (rows?.length !== 1 || rows[0].id !== id) throw Error("DURABLE_ROW_NOT_FOUND");
		},
		beforeSubmit: async () => {
			if (await activation()) throw Error("BOT_PAUSED");
			if (clock() > target + policy.maxEntryAgeMs || !quote || clock() - quote.requestStartedAt > policy.quoteMaxAgeMs) throw Error("PRE_SUBMIT_EXPIRED");
		},
		submit: async (body) => {
			const shard = (get("EXCHANGE_INDEX") || "-1").trim().toLowerCase();
			return c.exchange("POST", "/trade-api/v2/portfolio/events/orders", {
				...body,
				...shard === "omit" ? {} : { exchange_index: Number(shard) }
			});
		},
		read: (id, abort) => c.exchange("GET", "/trade-api/v2/portfolio/orders/" + encodeURIComponent(id), void 0, void 0, abort),
		cancel: (id, abort) => c.exchange("DELETE", "/trade-api/v2/portfolio/events/orders/" + encodeURIComponent(id), void 0, {
			market_ticker: ticker,
			...(get("EXCHANGE_INDEX") || "-1") === "omit" ? {} : { exchange_index: get("EXCHANGE_INDEX") || "-1" }
		}, abort),
		log
	}, policy, {
		ticker,
		side,
		target,
		received
	});
	await c.db("v12_shadow_signals?id=eq." + receipt.id, "PATCH", {
		execution_status: trace.status,
		execution_updated_at: new Date(clock()).toISOString(),
		bet_id: trace.bet_id || null
	});
	return trace;
}
//#endregion
export { EXECUTOR_REVISION, dayStart, executeV12, executionReadiness };
