import { z } from "zod";
const integer = z.string().regex(/^-?\d{1,30}$/);
const ms = z.number().int().nonnegative().safe();
const code = z.string().regex(/^[A-Za-z0-9 _.,:;/+()=-]{0,180}$/);
const id = z.string().max(180);
const hash = z.string().regex(/^[a-zA-Z0-9_-]{1,180}$/);
export const fillSchema = z.object({
  price_micros: integer,
  quantity_sats: integer,
  notional_micros: integer,
  fee_micros: integer,
  exchange_ms: ms,
  receipt_ms: ms,
  decision_ms: ms,
  fill_ms: ms,
  event_ms: ms,
  quote_sequence: integer,
  latency_ms: z.number().nonnegative(),
  bid_micros: integer,
  ask_micros: integer,
  slippage_bps: z.number(),
});
export const tradeSchema = z.object({
  id: ms,
  trade_id: id,
  position_id: id,
  symbol: z.enum(["BTCUSDT", "BTCUSD"]).optional(),
  side: z.enum(["LONG", "SHORT"]),
  entry: fillSchema,
  exit: fillSchema,
  closed_ms: ms,
  exit_reason: code,
  risk_micros: integer.optional(),
  planned_stop_risk_micros: integer.optional(),
  entry_notional_micros: integer.optional(),
  strategy_version: id.optional(),
  exposure_bps: z.number().optional(),
  gross_pnl_micros: integer,
  fees_micros: integer,
  carry_micros: integer.nullable(),
  net_pnl_micros: integer.nullable(),
  outcome: z.enum(["WIN", "LOSS", "FLAT", "PENDING"]),
  config_hash: hash,
  artifact_hash: hash,
});
// Only numeric, declared market features cross the public boundary. No arbitrary metadata.
const signalSchema = z.object({
  imbalance: z.number().optional(),
  volume_ratio: z.number().optional(),
  return_bps: z.number().optional(),
  spread_bps: z.number().optional(),
  price_bps: z.number().optional(),
  quote_age_ms: z.number().optional(),
  decision_ms: ms.optional(),
  window_ms: ms.optional(),
  trade_count: ms.optional(),
});
export const callSchema = z.object({
  id: ms,
  call_id: id,
  action: z.enum(["LONG", "SHORT", "EXIT", "ABSTAIN"]),
  reason: code,
  strategy_action: code,
  decision_ms: ms,
  bar_close_ms: ms,
  received_ms: ms,
  config_hash: hash,
  artifact_hash: hash,
  signal: signalSchema,
  strategy_version: id,
  risk_micros: integer,
  symbol: z.enum(["BTCUSDT", "BTCUSD"]).optional(),
});
export const pageSchema = <T extends z.ZodTypeAny>(item: T) =>
  z.object({ items: z.array(item).max(200), next_cursor: ms.nullable() });
export const snapshotSchema = z
  .object({
    schema_version: z.literal("dot-paper/v1"),
    run_id: z.string().uuid(),
    started_at_ms: ms,
    provenance: z.literal("FORWARD"),
    mode: z.literal("PAPER"),
    caller: z.literal("DOT"),
    symbol: z.enum(["BTCUSDT", "BTCUSD"]),
    server_ms: ms,
    state: z.enum([
      "EMPTY",
      "WAITING_FOR_DATA",
      "RUNNING",
      "PAUSED",
      "STALE",
      "CIRCUIT_BREAKER",
      "ERROR",
    ]),
    running_requested: z.boolean(),
    status_reason: code,
    strategy: z.object({
      version: id,
      config_hash: hash,
      strategy_hash: hash,
      artifact_hash: hash,
      validation: z.literal("EXPERIMENTAL_UNVALIDATED"),
      config: z
        .object({
          strategy_version: id.optional(),
          symbol: id.optional(),
          market: id.optional(),
          timeframe_ms: ms.optional(),
          baseline_bars: ms.optional(),
          flow_bars: ms.optional(),
          min_imbalance: z.number().optional(),
          min_volume_ratio: z.number().optional(),
          min_aligned_return_bps: z.number().optional(),
          max_aligned_return_bps: z.number().optional(),
          stop_bps: z.number().optional(),
          target_bps: z.number().optional(),
          max_hold_ms: ms.optional(),
          flow_exit_imbalance: z.number().optional(),
          max_notional_equity_fraction: z.number().optional(),
          max_leverage: z.number().optional(),
          daily_loss_limit_fraction: z.number().optional(),
          drawdown_halt_fraction: z.number().optional(),
          cooldown_ms: ms.optional(),
          entry_delay_ms: ms.optional(),
          fee_bps_per_side: z.number().optional(),
          half_spread_bps: z.number().optional(),
          slippage_bps_per_side: z.number().optional(),
          initial_paper_equity: z.number().optional(),
          long_only: z.boolean().optional(),
          research_only: z.boolean().optional(),
          promotion_status: code.optional(),
          live_orders_allowed: z.literal(false).optional(),
        })
        .optional(),
      calibration_venue: code.optional(),
      forward_venue: code.optional(),
      domain_shift: z.boolean().optional(),
    }),
    feed: z.object({
      source: code,
      enabled: z.boolean(),
      rights_approved: z.boolean(),
      health: z.enum(["UNKNOWN", "FRESH", "STALE", "DISCONNECTED", "DISABLED"]),
      reason: code,
      exchange_ms: ms.nullable(),
      event_ms: ms.nullable(),
      receipt_ms: ms.nullable(),
      processed_ms: ms.nullable(),
      quote_age_ms: z.number().nonnegative().nullable(),
      bid_micros: integer.nullable(),
      ask_micros: integer.nullable(),
      spread_bps: z.number().nullable(),
      bar_close_ms: ms.nullable(),
      warmup_bars: ms,
    }),
    simulator: z.object({
      health: z.enum(["READY", "BLOCKED", "DEGRADED"]),
      reason: code,
      last_decision_ms: ms.nullable(),
      last_fill_ms: ms.nullable(),
    }),
    account: z.object({
      currency: z.enum(["USD", "USDT"]),
      initial_equity_micros: integer,
      cash_micros: integer,
      realized_gross_micros: integer,
      realized_net_micros: integer,
      fees_paid_micros: integer,
      carry_paid_micros: integer,
      unrealized_net_micros: integer.nullable(),
      equity_micros: integer.nullable(),
      equity_mark_ms: ms.nullable(),
      last_known_equity_micros: integer.nullable(),
      wins: ms,
      losses: ms,
      flats: ms,
      closed_trades: ms,
      win_rate_pct: z.number().min(0).max(100).nullable(),
    }),
    risk: z.object({
      risk_bps: z.number(),
      max_exposure_bps: z.number(),
      daily_loss_limit_bps: z.number(),
      circuit_breaker: z.boolean(),
      daily_loss_micros: integer.nullable(),
      risk_budget_micros: integer,
      max_notional_micros: integer,
    }),
    assumptions: z.object({
      taker_fee_bps: z.number(),
      slippage_bps: z.number(),
      entry_latency_ms: ms,
      exit_latency_ms: ms,
      max_quote_age_ms: ms,
      max_spread_bps: z.number(),
      entry_timeout_ms: ms,
      fill_model: z.string().max(500),
      carry_model: z.string().max(500),
    }),
    equity: pageSchema(
      z.object({
        id: ms,
        at_ms: ms,
        equity_micros: integer,
        mark_ms: ms,
        source: z.literal("FORWARD_PAPER_MARK"),
        config_hash: hash,
      }),
    ),
    gates: z
      .array(z.object({ name: code, ok: z.boolean(), reason: code }))
      .max(30),
    position: z
      .object({
        position_id: id,
        call_id: id,
        side: z.enum(["LONG", "SHORT"]),
        opened_ms: ms,
        entry: fillSchema,
        quantity_sats: integer,
        stop_micros: integer,
        target_micros: integer,
        max_hold_ms: ms,
        risk_micros: integer,
        config_hash: hash,
        artifact_hash: hash,
      })
      .nullable(),
    pending: z
      .object({
        kind: z.enum(["ENTRY", "EXIT"]),
        side: z.enum(["LONG", "SHORT"]).optional(),
        reason: code,
        decision_ms: ms,
        eligible_ms: ms,
        expires_ms: ms.nullable(),
      })
      .nullable(),
    calls: pageSchema(callSchema),
    trades: pageSchema(tradeSchema),
  })
  .refine(
    (value) =>
      value.symbol === "BTCUSD"
        ? value.account.currency === "USD"
        : value.account.currency === "USDT",
    "Symbol and quote currency must match",
  )
  .transform((value) => ({
    ...value,
    audit: { items: [], next_cursor: null },
  }));
