/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedSettingsModelRouteImport } from './routes/_authenticated/settings.model'
import { Route as ApiPublicHooksScheduled15mRunRouteImport } from './routes/api/public/hooks/scheduled-15m-run'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsModelRoute =
  AuthenticatedSettingsModelRouteImport.update({
    id: '/settings/model',
    path: '/settings/model',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksScheduled15mRunRoute =
  ApiPublicHooksScheduled15mRunRouteImport.update({
    id: '/api/public/hooks/scheduled-15m-run',
    path: '/api/public/hooks/scheduled-15m-run',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/settings/model': typeof AuthenticatedSettingsModelRoute
  '/api/public/hooks/scheduled-15m-run': typeof ApiPublicHooksScheduled15mRunRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/': typeof AuthenticatedIndexRoute
  '/settings/model': typeof AuthenticatedSettingsModelRoute
  '/api/public/hooks/scheduled-15m-run': typeof ApiPublicHooksScheduled15mRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/settings/model': typeof AuthenticatedSettingsModelRoute
  '/api/public/hooks/scheduled-15m-run': typeof ApiPublicHooksScheduled15mRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/history'
    | '/stats'
    | '/settings/model'
    | '/api/public/hooks/scheduled-15m-run'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/history'
    | '/stats'
    | '/'
    | '/settings/model'
    | '/api/public/hooks/scheduled-15m-run'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/history'
    | '/_authenticated/stats'
    | '/_authenticated/'
    | '/_authenticated/settings/model'
    | '/api/public/hooks/scheduled-15m-run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksScheduled15mRunRoute: typeof ApiPublicHooksScheduled15mRunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/model': {
      id: '/_authenticated/settings/model'
      path: '/settings/model'
      fullPath: '/settings/model'
      preLoaderRoute: typeof AuthenticatedSettingsModelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/scheduled-15m-run': {
      id: '/api/public/hooks/scheduled-15m-run'
      path: '/api/public/hooks/scheduled-15m-run'
      fullPath: '/api/public/hooks/scheduled-15m-run'
      preLoaderRoute: typeof ApiPublicHooksScheduled15mRunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSettingsModelRoute: typeof AuthenticatedSettingsModelRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSettingsModelRoute: AuthenticatedSettingsModelRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksScheduled15mRunRoute: ApiPublicHooksScheduled15mRunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
