ALTER TABLE public.v6_predictions
  ADD COLUMN IF NOT EXISTS r7_version text,
  ADD COLUMN IF NOT EXISTS r7_model_revision text,
  ADD COLUMN IF NOT EXISTS r7_activated_at timestamptz,
  ADD COLUMN IF NOT EXISTS r7_shadow_enabled boolean,
  ADD COLUMN IF NOT EXISTS r7_publication_enabled boolean,
  ADD COLUMN IF NOT EXISTS r7_state_evaluable boolean,
  ADD COLUMN IF NOT EXISTS r7_broad_bin integer,
  ADD COLUMN IF NOT EXISTS r7_anchor_bin integer,
  ADD COLUMN IF NOT EXISTS r7_state_id text,
  ADD COLUMN IF NOT EXISTS r7_history_window integer,
  ADD COLUMN IF NOT EXISTS r7_history_ready boolean,
  ADD COLUMN IF NOT EXISTS r7_history_error text,
  ADD COLUMN IF NOT EXISTS r7_prior_valid_opportunity_count integer,
  ADD COLUMN IF NOT EXISTS r7_state_sample_count integer,
  ADD COLUMN IF NOT EXISTS r7_state_green_count integer,
  ADD COLUMN IF NOT EXISTS r7_state_red_count integer,
  ADD COLUMN IF NOT EXISTS r7_state_green_win_rate double precision,
  ADD COLUMN IF NOT EXISTS r7_state_red_win_rate double precision,
  ADD COLUMN IF NOT EXISTS r7_e4_candidate text,
  ADD COLUMN IF NOT EXISTS r7_e1_candidate text,
  ADD COLUMN IF NOT EXISTS r7_e1_state_samples integer,
  ADD COLUMN IF NOT EXISTS r7_e1_state_wins integer,
  ADD COLUMN IF NOT EXISTS r7_e1_state_losses integer,
  ADD COLUMN IF NOT EXISTS r7_e1_state_raw_net integer,
  ADD COLUMN IF NOT EXISTS r7_e1_state_win_rate double precision,
  ADD COLUMN IF NOT EXISTS r7_e1_state_edge_rate double precision,
  ADD COLUMN IF NOT EXISTS r7_e1_qualified boolean,
  ADD COLUMN IF NOT EXISTS r7_e2_candidate text,
  ADD COLUMN IF NOT EXISTS r7_e2_state_samples integer,
  ADD COLUMN IF NOT EXISTS r7_e2_state_wins integer,
  ADD COLUMN IF NOT EXISTS r7_e2_state_losses integer,
  ADD COLUMN IF NOT EXISTS r7_e2_state_raw_net integer,
  ADD COLUMN IF NOT EXISTS r7_e2_state_win_rate double precision,
  ADD COLUMN IF NOT EXISTS r7_e2_state_edge_rate double precision,
  ADD COLUMN IF NOT EXISTS r7_e2_qualified boolean,
  ADD COLUMN IF NOT EXISTS r7_e3_candidate text,
  ADD COLUMN IF NOT EXISTS r7_e3_state_samples integer,
  ADD COLUMN IF NOT EXISTS r7_e3_state_wins integer,
  ADD COLUMN IF NOT EXISTS r7_e3_state_losses integer,
  ADD COLUMN IF NOT EXISTS r7_e3_state_raw_net integer,
  ADD COLUMN IF NOT EXISTS r7_e3_state_win_rate double precision,
  ADD COLUMN IF NOT EXISTS r7_e3_state_edge_rate double precision,
  ADD COLUMN IF NOT EXISTS r7_e3_qualified boolean,
  ADD COLUMN IF NOT EXISTS r7_e4_state_samples integer,
  ADD COLUMN IF NOT EXISTS r7_e4_state_wins integer,
  ADD COLUMN IF NOT EXISTS r7_e4_state_losses integer,
  ADD COLUMN IF NOT EXISTS r7_e4_state_raw_net integer,
  ADD COLUMN IF NOT EXISTS r7_e4_state_win_rate double precision,
  ADD COLUMN IF NOT EXISTS r7_e4_state_edge_rate double precision,
  ADD COLUMN IF NOT EXISTS r7_e4_qualified boolean,
  ADD COLUMN IF NOT EXISTS r7_best_green_expert text,
  ADD COLUMN IF NOT EXISTS r7_best_green_edge_rate double precision,
  ADD COLUMN IF NOT EXISTS r7_best_green_samples integer,
  ADD COLUMN IF NOT EXISTS r7_best_red_expert text,
  ADD COLUMN IF NOT EXISTS r7_best_red_edge_rate double precision,
  ADD COLUMN IF NOT EXISTS r7_best_red_samples integer,
  ADD COLUMN IF NOT EXISTS r7_selected_expert text,
  ADD COLUMN IF NOT EXISTS r7_shadow_prediction text,
  ADD COLUMN IF NOT EXISTS r7_shadow_reason text,
  ADD COLUMN IF NOT EXISTS r7_r6_reference_prediction text,
  ADD COLUMN IF NOT EXISTS r7_action_vs_r6 text,
  ADD COLUMN IF NOT EXISTS r7_shadow_result text,
  ADD COLUMN IF NOT EXISTS r7_shadow_raw_score double precision,
  ADD COLUMN IF NOT EXISTS r7_raw_contribution_vs_r6 double precision,
  ADD COLUMN IF NOT EXISTS r7_e1_shadow_result text,
  ADD COLUMN IF NOT EXISTS r7_e1_shadow_raw_score double precision,
  ADD COLUMN IF NOT EXISTS r7_e2_shadow_result text,
  ADD COLUMN IF NOT EXISTS r7_e2_shadow_raw_score double precision,
  ADD COLUMN IF NOT EXISTS r7_e3_shadow_result text,
  ADD COLUMN IF NOT EXISTS r7_e3_shadow_raw_score double precision,
  ADD COLUMN IF NOT EXISTS r7_e4_shadow_result text,
  ADD COLUMN IF NOT EXISTS r7_e4_shadow_raw_score double precision;

CREATE INDEX IF NOT EXISTS v6_predictions_r7_state_idx
  ON public.v6_predictions (r7_state_id, target_candle_ts DESC);