ALTER TABLE public.b4x4_es1_predictions
  ADD COLUMN IF NOT EXISTS precision_policy_id text,
  ADD COLUMN IF NOT EXISTS precision_policy_version text,
  ADD COLUMN IF NOT EXISTS precision_implementation_revision text,
  ADD COLUMN IF NOT EXISTS precision_config_hash text,
  ADD COLUMN IF NOT EXISTS precision_activation_id text,
  ADD COLUMN IF NOT EXISTS precision_activation_target_ts timestamptz,
  ADD COLUMN IF NOT EXISTS precision_activated boolean,
  ADD COLUMN IF NOT EXISTS precision_input_hash text,
  ADD COLUMN IF NOT EXISTS precision_opportunity_index integer,
  ADD COLUMN IF NOT EXISTS precision_ready boolean,
  ADD COLUMN IF NOT EXISTS precision_ready_reason text,
  ADD COLUMN IF NOT EXISTS precision_spot_ready boolean,
  ADD COLUMN IF NOT EXISTS precision_perp_ready boolean,
  ADD COLUMN IF NOT EXISTS precision_spot_mode text,
  ADD COLUMN IF NOT EXISTS precision_spot_direction text,
  ADD COLUMN IF NOT EXISTS precision_perp_mode text,
  ADD COLUMN IF NOT EXISTS precision_perp_direction text,
  ADD COLUMN IF NOT EXISTS precision_venue_agreement boolean,
  ADD COLUMN IF NOT EXISTS precision_activity_guard_passed boolean,
  ADD COLUMN IF NOT EXISTS precision_spot_final_imbalance_10bps double precision,
  ADD COLUMN IF NOT EXISTS precision_spot_mean_imbalance_10bps_60s double precision,
  ADD COLUMN IF NOT EXISTS precision_perp_final_imbalance_10bps double precision,
  ADD COLUMN IF NOT EXISTS precision_perp_mean_imbalance_10bps_60s double precision,
  ADD COLUMN IF NOT EXISTS precision_perp_sign_change_count_60s integer,
  ADD COLUMN IF NOT EXISTS precision_spot_normalized_ofi_5s double precision,
  ADD COLUMN IF NOT EXISTS precision_technical_direction text,
  ADD COLUMN IF NOT EXISTS precision_technical_confidence double precision,
  ADD COLUMN IF NOT EXISTS precision_technical_p_green double precision,
  ADD COLUMN IF NOT EXISTS precision_technical_train_rows integer,
  ADD COLUMN IF NOT EXISTS precision_technical_model_available boolean,
  ADD COLUMN IF NOT EXISTS precision_technical_error text,
  ADD COLUMN IF NOT EXISTS precision_balanced_route text,
  ADD COLUMN IF NOT EXISTS precision_balanced_would_trade boolean,
  ADD COLUMN IF NOT EXISTS precision_balanced_direction text,
  ADD COLUMN IF NOT EXISTS precision_prior_trend_age_candles double precision,
  ADD COLUMN IF NOT EXISTS precision_upper_wick_percentile_96 double precision,
  ADD COLUMN IF NOT EXISTS precision_primary_would_trade boolean,
  ADD COLUMN IF NOT EXISTS precision_primary_direction text,
  ADD COLUMN IF NOT EXISTS precision_rescue_would_trade boolean,
  ADD COLUMN IF NOT EXISTS precision_rescue_direction text,
  ADD COLUMN IF NOT EXISTS precision_sleeve text,
  ADD COLUMN IF NOT EXISTS precision_would_trade boolean,
  ADD COLUMN IF NOT EXISTS precision_candidate_direction text,
  ADD COLUMN IF NOT EXISTS precision_decision_reason text,
  ADD COLUMN IF NOT EXISTS precision_webhook_eligible boolean,
  ADD COLUMN IF NOT EXISTS precision_webhook_sent_at timestamptz,
  ADD COLUMN IF NOT EXISTS precision_result text,
  ADD COLUMN IF NOT EXISTS precision_result_score integer,
  ADD COLUMN IF NOT EXISTS precision_balanced_result text,
  ADD COLUMN IF NOT EXISTS precision_balanced_result_score integer,
  ADD COLUMN IF NOT EXISTS precision_resolved_at timestamptz,
  ADD COLUMN IF NOT EXISTS precision_resolver_version text,
  ADD COLUMN IF NOT EXISTS precision_resolution_attempt_count integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS precision_build_ms integer;

ALTER TABLE public.b4x4_es1_activation
  ADD COLUMN IF NOT EXISTS precision_mode text,
  ADD COLUMN IF NOT EXISTS precision_policy_id text,
  ADD COLUMN IF NOT EXISTS precision_policy_version text,
  ADD COLUMN IF NOT EXISTS precision_config_hash text,
  ADD COLUMN IF NOT EXISTS precision_approved_at timestamptz,
  ADD COLUMN IF NOT EXISTS precision_approval_note text,
  ADD COLUMN IF NOT EXISTS precision_activation_target_ts timestamptz,
  ADD COLUMN IF NOT EXISTS precision_activation_snapshot jsonb,
  ADD COLUMN IF NOT EXISTS precision_created_at timestamptz;