ALTER TABLE public.v6_predictions
  ADD COLUMN IF NOT EXISTS r5_router_version text,
  ADD COLUMN IF NOT EXISTS r5_green_evaluable boolean,
  ADD COLUMN IF NOT EXISTS r5_green_candidate boolean,
  ADD COLUMN IF NOT EXISTS r5_green_stoch_spread double precision,
  ADD COLUMN IF NOT EXISTS r5_green_stoch_spread_threshold double precision,
  ADD COLUMN IF NOT EXISTS r5_green_stoch_condition boolean,
  ADD COLUMN IF NOT EXISTS r5_green_d1_mean_body_to_range_2 double precision,
  ADD COLUMN IF NOT EXISTS r5_green_d1_mean_body_to_range_2_threshold double precision,
  ADD COLUMN IF NOT EXISTS r5_green_body_condition boolean,
  ADD COLUMN IF NOT EXISTS r5_red_feeder_evaluable boolean,
  ADD COLUMN IF NOT EXISTS r5_red_feeder_pass boolean,
  ADD COLUMN IF NOT EXISTS r5_red_feeder_prediction text,
  ADD COLUMN IF NOT EXISTS r5_red_feeder_source text,
  ADD COLUMN IF NOT EXISTS r5_red_anchor_evaluable boolean,
  ADD COLUMN IF NOT EXISTS r5_red_anchor_candidate boolean,
  ADD COLUMN IF NOT EXISTS r5_red_anchor_d1_close_position double precision,
  ADD COLUMN IF NOT EXISTS r5_red_anchor_d1_close_position_threshold double precision,
  ADD COLUMN IF NOT EXISTS r5_red_anchor_condition boolean,
  ADD COLUMN IF NOT EXISTS r5_red_broad_evaluable boolean,
  ADD COLUMN IF NOT EXISTS r5_red_broad_candidate boolean,
  ADD COLUMN IF NOT EXISTS r5_red_broad_close_slope_8 double precision,
  ADD COLUMN IF NOT EXISTS r5_red_broad_close_slope_threshold double precision,
  ADD COLUMN IF NOT EXISTS r5_red_broad_slope_condition boolean,
  ADD COLUMN IF NOT EXISTS r5_red_broad_bb_width_pct double precision,
  ADD COLUMN IF NOT EXISTS r5_red_broad_bb_width_threshold double precision,
  ADD COLUMN IF NOT EXISTS r5_red_broad_bb_condition boolean,
  ADD COLUMN IF NOT EXISTS r5_red_candidate boolean,
  ADD COLUMN IF NOT EXISTS r5_conflict boolean,
  ADD COLUMN IF NOT EXISTS r5_router_decision text,
  ADD COLUMN IF NOT EXISTS r5_router_source text,
  ADD COLUMN IF NOT EXISTS r5_router_reason text,
  ADD COLUMN IF NOT EXISTS final_reason text,
  ADD COLUMN IF NOT EXISTS r5_final_result text,
  ADD COLUMN IF NOT EXISTS r5_final_raw_score double precision,
  ADD COLUMN IF NOT EXISTS r5_final_adjusted_score double precision,
  ADD COLUMN IF NOT EXISTS r5_green_shadow_prediction text,
  ADD COLUMN IF NOT EXISTS r5_green_shadow_result text,
  ADD COLUMN IF NOT EXISTS r5_green_shadow_raw_score double precision,
  ADD COLUMN IF NOT EXISTS r5_green_shadow_adjusted_score double precision,
  ADD COLUMN IF NOT EXISTS r5_red_anchor_shadow_prediction text,
  ADD COLUMN IF NOT EXISTS r5_red_anchor_shadow_result text,
  ADD COLUMN IF NOT EXISTS r5_red_anchor_shadow_raw_score double precision,
  ADD COLUMN IF NOT EXISTS r5_red_anchor_shadow_adjusted_score double precision,
  ADD COLUMN IF NOT EXISTS r5_red_broad_shadow_prediction text,
  ADD COLUMN IF NOT EXISTS r5_red_broad_shadow_result text,
  ADD COLUMN IF NOT EXISTS r5_red_broad_shadow_raw_score double precision,
  ADD COLUMN IF NOT EXISTS r5_red_broad_shadow_adjusted_score double precision,
  ADD COLUMN IF NOT EXISTS r5_conflict_green_result text,
  ADD COLUMN IF NOT EXISTS r5_conflict_red_result text,
  ADD COLUMN IF NOT EXISTS r5_aligned_wick_red_shadow_evaluable boolean,
  ADD COLUMN IF NOT EXISTS r5_aligned_wick_red_shadow_candidate boolean,
  ADD COLUMN IF NOT EXISTS r5_aligned_wick_red_shadow_value double precision,
  ADD COLUMN IF NOT EXISTS r5_aligned_wick_red_shadow_threshold double precision,
  ADD COLUMN IF NOT EXISTS r5_aligned_wick_red_shadow_result text,
  ADD COLUMN IF NOT EXISTS r5_aligned_wick_red_shadow_raw_score double precision,
  ADD COLUMN IF NOT EXISTS r5_aligned_wick_red_shadow_adjusted_score double precision,
  ADD COLUMN IF NOT EXISTS legacy_pickup_publication_enabled boolean,
  ADD COLUMN IF NOT EXISTS broad_conflict_publication_enabled boolean,
  ADD COLUMN IF NOT EXISTS broad_red_reliability_publication_enabled boolean,
  ADD COLUMN IF NOT EXISTS structure_confirmation_shadow_only boolean,
  ADD COLUMN IF NOT EXISTS structure_confirmation_publication_enabled boolean,
  ADD COLUMN IF NOT EXISTS legacy_r4_shadow_prediction text,
  ADD COLUMN IF NOT EXISTS legacy_r4_shadow_source text,
  ADD COLUMN IF NOT EXISTS legacy_r4_shadow_reason text,
  ADD COLUMN IF NOT EXISTS legacy_r4_shadow_result text,
  ADD COLUMN IF NOT EXISTS legacy_r4_shadow_raw_score double precision,
  ADD COLUMN IF NOT EXISTS legacy_r4_shadow_adjusted_score double precision,
  ADD COLUMN IF NOT EXISTS consensus_red_shadow_prediction text,
  ADD COLUMN IF NOT EXISTS consensus_red_shadow_result text,
  ADD COLUMN IF NOT EXISTS consensus_red_shadow_raw_score double precision,
  ADD COLUMN IF NOT EXISTS consensus_red_shadow_adjusted_score double precision,
  ADD COLUMN IF NOT EXISTS momentum_green_shadow_prediction text,
  ADD COLUMN IF NOT EXISTS momentum_green_shadow_result text,
  ADD COLUMN IF NOT EXISTS momentum_green_shadow_raw_score double precision,
  ADD COLUMN IF NOT EXISTS momentum_green_shadow_adjusted_score double precision;