ALTER TABLE public.b4x4_predictions
  ADD COLUMN IF NOT EXISTS saturation_calibration_version text,
  ADD COLUMN IF NOT EXISTS saturation_window integer,
  ADD COLUMN IF NOT EXISTS saturation_history_count integer,
  ADD COLUMN IF NOT EXISTS saturation_history_start_ts timestamptz,
  ADD COLUMN IF NOT EXISTS saturation_history_end_ts timestamptz,
  ADD COLUMN IF NOT EXISTS saturation_ready boolean,
  ADD COLUMN IF NOT EXISTS saturation_current_raw_direction text,
  ADD COLUMN IF NOT EXISTS saturation_same_side_count integer,
  ADD COLUMN IF NOT EXISTS saturation_same_side_share double precision,
  ADD COLUMN IF NOT EXISTS saturation_mean_aligned_confidence double precision,
  ADD COLUMN IF NOT EXISTS saturation_index double precision,
  ADD COLUMN IF NOT EXISTS saturation_trigger_threshold double precision,
  ADD COLUMN IF NOT EXISTS saturation_cap_slope double precision,
  ADD COLUMN IF NOT EXISTS saturation_min_confidence_cap double precision,
  ADD COLUMN IF NOT EXISTS saturation_current_aligned_confidence double precision,
  ADD COLUMN IF NOT EXISTS saturation_dynamic_confidence_cap double precision,
  ADD COLUMN IF NOT EXISTS saturation_regime_active boolean,
  ADD COLUMN IF NOT EXISTS saturation_candidate_before boolean,
  ADD COLUMN IF NOT EXISTS saturation_candidate_source_before text,
  ADD COLUMN IF NOT EXISTS saturation_condition_met boolean,
  ADD COLUMN IF NOT EXISTS saturation_veto_fired boolean,
  ADD COLUMN IF NOT EXISTS saturation_candidate_after boolean,
  ADD COLUMN IF NOT EXISTS saturation_reason text,
  ADD COLUMN IF NOT EXISTS without_saturation_decision text,
  ADD COLUMN IF NOT EXISTS without_saturation_direction text,
  ADD COLUMN IF NOT EXISTS without_saturation_skip_reason text,
  ADD COLUMN IF NOT EXISTS without_saturation_score double precision,
  ADD COLUMN IF NOT EXISTS saturation_attribution_class text,
  ADD COLUMN IF NOT EXISTS saturation_incremental_value double precision,
  ADD COLUMN IF NOT EXISTS saturation_incremental_change boolean;