ALTER TABLE public.v6_predictions
  ADD COLUMN IF NOT EXISTS r6_router_version text,
  ADD COLUMN IF NOT EXISTS r6_base_prediction text,
  ADD COLUMN IF NOT EXISTS r6_base_source text,
  ADD COLUMN IF NOT EXISTS r6_base_reason text,
  ADD COLUMN IF NOT EXISTS r5_route_brake_shadow_only boolean,
  ADD COLUMN IF NOT EXISTS r5_route_brake_publication_enabled boolean,
  ADD COLUMN IF NOT EXISTS r5_route_brake_shadow_prediction text,
  ADD COLUMN IF NOT EXISTS r5_route_brake_shadow_reason text,
  ADD COLUMN IF NOT EXISTS r5_route_brake_shadow_result text,
  ADD COLUMN IF NOT EXISTS r5_route_brake_shadow_raw_score double precision,
  ADD COLUMN IF NOT EXISTS r5_route_brake_shadow_adjusted_score double precision,
  ADD COLUMN IF NOT EXISTS r6_p1_evaluable boolean,
  ADD COLUMN IF NOT EXISTS r6_p1_green_candidate boolean,
  ADD COLUMN IF NOT EXISTS r6_p1_path_efficiency_4 double precision,
  ADD COLUMN IF NOT EXISTS r6_p1_path_efficiency_threshold double precision,
  ADD COLUMN IF NOT EXISTS r6_p1_momentum_8_over_atr double precision,
  ADD COLUMN IF NOT EXISTS r6_p1_momentum_threshold double precision,
  ADD COLUMN IF NOT EXISTS r6_p1_condition_a boolean,
  ADD COLUMN IF NOT EXISTS r6_p1_condition_b boolean,
  ADD COLUMN IF NOT EXISTS r6_p1_shadow_result text,
  ADD COLUMN IF NOT EXISTS r6_p1_shadow_raw_score double precision,
  ADD COLUMN IF NOT EXISTS r6_p1_shadow_adjusted_score double precision,
  ADD COLUMN IF NOT EXISTS r6_p2_evaluable boolean,
  ADD COLUMN IF NOT EXISTS r6_p2_red_candidate boolean,
  ADD COLUMN IF NOT EXISTS r6_p2_roc_8 double precision,
  ADD COLUMN IF NOT EXISTS r6_p2_roc_threshold double precision,
  ADD COLUMN IF NOT EXISTS r6_p2_volume_expansion double precision,
  ADD COLUMN IF NOT EXISTS r6_p2_volume_expansion_threshold double precision,
  ADD COLUMN IF NOT EXISTS r6_p2_condition_a boolean,
  ADD COLUMN IF NOT EXISTS r6_p2_condition_b boolean,
  ADD COLUMN IF NOT EXISTS r6_p2_shadow_result text,
  ADD COLUMN IF NOT EXISTS r6_p2_shadow_raw_score double precision,
  ADD COLUMN IF NOT EXISTS r6_p2_shadow_adjusted_score double precision,
  ADD COLUMN IF NOT EXISTS r6_p3_evaluable boolean,
  ADD COLUMN IF NOT EXISTS r6_p3_green_candidate boolean,
  ADD COLUMN IF NOT EXISTS r6_p3_channel_position_0_1 double precision,
  ADD COLUMN IF NOT EXISTS r6_p3_channel_position_threshold double precision,
  ADD COLUMN IF NOT EXISTS r6_p3_change_pct double precision,
  ADD COLUMN IF NOT EXISTS r6_p3_change_pct_threshold double precision,
  ADD COLUMN IF NOT EXISTS r6_p3_condition_a boolean,
  ADD COLUMN IF NOT EXISTS r6_p3_condition_b boolean,
  ADD COLUMN IF NOT EXISTS r6_p3_shadow_result text,
  ADD COLUMN IF NOT EXISTS r6_p3_shadow_raw_score double precision,
  ADD COLUMN IF NOT EXISTS r6_p3_shadow_adjusted_score double precision,
  ADD COLUMN IF NOT EXISTS r6_p4_evaluable boolean,
  ADD COLUMN IF NOT EXISTS r6_p4_red_candidate boolean,
  ADD COLUMN IF NOT EXISTS r6_p4_mean_body_to_range_2 double precision,
  ADD COLUMN IF NOT EXISTS r6_p4_mean_body_threshold double precision,
  ADD COLUMN IF NOT EXISTS r6_p4_macd_hist_over_atr14 double precision,
  ADD COLUMN IF NOT EXISTS r6_p4_macd_threshold double precision,
  ADD COLUMN IF NOT EXISTS r6_p4_condition_a boolean,
  ADD COLUMN IF NOT EXISTS r6_p4_condition_b boolean,
  ADD COLUMN IF NOT EXISTS r6_p4_shadow_result text,
  ADD COLUMN IF NOT EXISTS r6_p4_shadow_raw_score double precision,
  ADD COLUMN IF NOT EXISTS r6_p4_shadow_adjusted_score double precision,
  ADD COLUMN IF NOT EXISTS r6_p5_evaluable boolean,
  ADD COLUMN IF NOT EXISTS r6_p5_green_candidate boolean,
  ADD COLUMN IF NOT EXISTS r6_p5_dist_to_low20_pct double precision,
  ADD COLUMN IF NOT EXISTS r6_p5_dist_low20_threshold double precision,
  ADD COLUMN IF NOT EXISTS r6_p5_change_pct double precision,
  ADD COLUMN IF NOT EXISTS r6_p5_change_pct_threshold double precision,
  ADD COLUMN IF NOT EXISTS r6_p5_condition_a boolean,
  ADD COLUMN IF NOT EXISTS r6_p5_condition_b boolean,
  ADD COLUMN IF NOT EXISTS r6_p5_shadow_result text,
  ADD COLUMN IF NOT EXISTS r6_p5_shadow_raw_score double precision,
  ADD COLUMN IF NOT EXISTS r6_p5_shadow_adjusted_score double precision,
  ADD COLUMN IF NOT EXISTS r6_p6_evaluable boolean,
  ADD COLUMN IF NOT EXISTS r6_p6_green_candidate boolean,
  ADD COLUMN IF NOT EXISTS r6_p6_path_efficiency_4 double precision,
  ADD COLUMN IF NOT EXISTS r6_p6_path_efficiency_threshold double precision,
  ADD COLUMN IF NOT EXISTS r6_p6_mean_body_to_range_2 double precision,
  ADD COLUMN IF NOT EXISTS r6_p6_mean_body_threshold double precision,
  ADD COLUMN IF NOT EXISTS r6_p6_condition_a boolean,
  ADD COLUMN IF NOT EXISTS r6_p6_condition_b boolean,
  ADD COLUMN IF NOT EXISTS r6_p6_shadow_result text,
  ADD COLUMN IF NOT EXISTS r6_p6_shadow_raw_score double precision,
  ADD COLUMN IF NOT EXISTS r6_p6_shadow_adjusted_score double precision,
  ADD COLUMN IF NOT EXISTS r6_green_promotion_candidate boolean,
  ADD COLUMN IF NOT EXISTS r6_red_promotion_candidate boolean,
  ADD COLUMN IF NOT EXISTS r6_green_promotion_rule_count integer,
  ADD COLUMN IF NOT EXISTS r6_red_promotion_rule_count integer,
  ADD COLUMN IF NOT EXISTS r6_green_promotion_rules_triggered jsonb,
  ADD COLUMN IF NOT EXISTS r6_red_promotion_rules_triggered jsonb,
  ADD COLUMN IF NOT EXISTS r6_promotion_conflict boolean,
  ADD COLUMN IF NOT EXISTS r6_promotion_primary_rule text,
  ADD COLUMN IF NOT EXISTS r6_promotion_all_rules jsonb,
  ADD COLUMN IF NOT EXISTS r6_final_prediction text,
  ADD COLUMN IF NOT EXISTS r6_final_source text,
  ADD COLUMN IF NOT EXISTS r6_final_reason text,
  ADD COLUMN IF NOT EXISTS r6_green_promotion_shadow_result text,
  ADD COLUMN IF NOT EXISTS r6_green_promotion_shadow_raw_score double precision,
  ADD COLUMN IF NOT EXISTS r6_green_promotion_shadow_adjusted_score double precision,
  ADD COLUMN IF NOT EXISTS r6_red_promotion_shadow_result text,
  ADD COLUMN IF NOT EXISTS r6_red_promotion_shadow_raw_score double precision,
  ADD COLUMN IF NOT EXISTS r6_red_promotion_shadow_adjusted_score double precision,
  ADD COLUMN IF NOT EXISTS r6_final_result text,
  ADD COLUMN IF NOT EXISTS r6_final_raw_score double precision,
  ADD COLUMN IF NOT EXISTS r6_final_adjusted_score double precision,
  ADD COLUMN IF NOT EXISTS r6_conflict_green_result text,
  ADD COLUMN IF NOT EXISTS r6_conflict_red_result text,
  ADD COLUMN IF NOT EXISTS r6_promotion_underlying_r5_prediction text,
  ADD COLUMN IF NOT EXISTS r6_promotion_final_prediction text,
  ADD COLUMN IF NOT EXISTS r6_promotion_result text,
  ADD COLUMN IF NOT EXISTS r6_promotion_raw_contribution double precision,
  ADD COLUMN IF NOT EXISTS r6_promotion_adjusted_contribution double precision,
  ADD COLUMN IF NOT EXISTS r6_base_r5_result text,
  ADD COLUMN IF NOT EXISTS r6_base_r5_raw_score double precision,
  ADD COLUMN IF NOT EXISTS r6_base_r5_adjusted_score double precision;