ALTER TABLE public.model7_td1_rc_shadow
  ADD COLUMN IF NOT EXISTS td1_policy_version text,
  ADD COLUMN IF NOT EXISTS td1_compressed_risk_threshold double precision,
  ADD COLUMN IF NOT EXISTS td1_compressed_risk_market_condition text,
  ADD COLUMN IF NOT EXISTS td1_compressed_risk_source_prediction_row_id text,
  ADD COLUMN IF NOT EXISTS td1_compressed_risk_evaluable boolean,
  ADD COLUMN IF NOT EXISTS td1_compressed_risk_condition boolean,
  ADD COLUMN IF NOT EXISTS td1_compressed_risk_veto_fired boolean,
  ADD COLUMN IF NOT EXISTS td1_compressed_risk_reason text,
  ADD COLUMN IF NOT EXISTS td1_compressed_risk_probability double precision,
  ADD COLUMN IF NOT EXISTS td1_legacy_global_veto_condition boolean,
  ADD COLUMN IF NOT EXISTS td1_compressed_risk_counterfactual_direction text,
  ADD COLUMN IF NOT EXISTS td1_compressed_risk_counterfactual_result text,
  ADD COLUMN IF NOT EXISTS td1_compressed_risk_counterfactual_score double precision,
  ADD COLUMN IF NOT EXISTS td1_compressed_risk_veto_value double precision,
  ADD COLUMN IF NOT EXISTS td1_prev_policy_decision text,
  ADD COLUMN IF NOT EXISTS td1_prev_policy_would_trade boolean,
  ADD COLUMN IF NOT EXISTS td1_prev_policy_result text,
  ADD COLUMN IF NOT EXISTS td1_prev_policy_score double precision,
  ADD COLUMN IF NOT EXISTS td1_no_global_veto_decision text,
  ADD COLUMN IF NOT EXISTS td1_no_global_veto_would_trade boolean,
  ADD COLUMN IF NOT EXISTS td1_no_global_veto_result text,
  ADD COLUMN IF NOT EXISTS td1_no_global_veto_score double precision;