ALTER TABLE public.v6_predictions
  ADD COLUMN IF NOT EXISTS selected_component text,
  ADD COLUMN IF NOT EXISTS broad_distance_from_neutral double precision,
  ADD COLUMN IF NOT EXISTS anchor_distance_from_neutral double precision,
  ADD COLUMN IF NOT EXISTS broad_conflict_veto_evaluable boolean,
  ADD COLUMN IF NOT EXISTS broad_conflict_veto_triggered boolean,
  ADD COLUMN IF NOT EXISTS broad_conflict_veto_reason text,
  ADD COLUMN IF NOT EXISTS broad_conflict_original_prediction text,
  ADD COLUMN IF NOT EXISTS broad_conflict_original_source text,
  ADD COLUMN IF NOT EXISTS broad_conflict_anchor_percentile double precision,
  ADD COLUMN IF NOT EXISTS broad_conflict_anchor_direction text,
  ADD COLUMN IF NOT EXISTS broad_conflict_anchor_distance double precision,
  ADD COLUMN IF NOT EXISTS broad_conflict_min_distance double precision,
  ADD COLUMN IF NOT EXISTS broad_conflict_max_distance double precision,
  ADD COLUMN IF NOT EXISTS prediction_after_broad_conflict_veto text,
  ADD COLUMN IF NOT EXISTS prediction_source_after_broad_conflict_veto text,
  ADD COLUMN IF NOT EXISTS broad_red_reliability_evaluable boolean,
  ADD COLUMN IF NOT EXISTS broad_red_reliability_ready boolean,
  ADD COLUMN IF NOT EXISTS broad_red_reliability_veto_active boolean,
  ADD COLUMN IF NOT EXISTS broad_red_reliability_veto_triggered boolean,
  ADD COLUMN IF NOT EXISTS broad_red_reliability_reason text,
  ADD COLUMN IF NOT EXISTS broad_red_history_count integer,
  ADD COLUMN IF NOT EXISTS broad_red_history_json jsonb,
  ADD COLUMN IF NOT EXISTS broad_red_last12_wins integer,
  ADD COLUMN IF NOT EXISTS broad_red_last12_losses integer,
  ADD COLUMN IF NOT EXISTS broad_red_last12_adjusted_net double precision,
  ADD COLUMN IF NOT EXISTS broad_red_reliability_threshold double precision,
  ADD COLUMN IF NOT EXISTS prediction_after_broad_red_reliability text,
  ADD COLUMN IF NOT EXISTS prediction_source_after_broad_red_reliability text,
  ADD COLUMN IF NOT EXISTS regime_inverter_shadow_only boolean,
  ADD COLUMN IF NOT EXISTS regime_inverter_publication_enabled boolean,
  ADD COLUMN IF NOT EXISTS regime_inverter_would_trigger boolean,
  ADD COLUMN IF NOT EXISTS regime_inverter_would_publish text,
  ADD COLUMN IF NOT EXISTS broad_conflict_underlying_prediction text,
  ADD COLUMN IF NOT EXISTS broad_conflict_underlying_raw_score double precision,
  ADD COLUMN IF NOT EXISTS broad_conflict_underlying_adjusted_score double precision,
  ADD COLUMN IF NOT EXISTS broad_conflict_veto_raw_contribution double precision,
  ADD COLUMN IF NOT EXISTS broad_conflict_veto_adjusted_contribution double precision,
  ADD COLUMN IF NOT EXISTS broad_red_underlying_prediction text,
  ADD COLUMN IF NOT EXISTS broad_red_underlying_raw_score double precision,
  ADD COLUMN IF NOT EXISTS broad_red_underlying_adjusted_score double precision,
  ADD COLUMN IF NOT EXISTS broad_red_reliability_raw_contribution double precision,
  ADD COLUMN IF NOT EXISTS broad_red_reliability_adjusted_contribution double precision,
  ADD COLUMN IF NOT EXISTS broad_red_shadow_prediction text,
  ADD COLUMN IF NOT EXISTS broad_red_shadow_adjusted_score double precision,
  ADD COLUMN IF NOT EXISTS regime_inverter_shadow_raw_score double precision,
  ADD COLUMN IF NOT EXISTS regime_inverter_shadow_adjusted_score double precision,
  ADD COLUMN IF NOT EXISTS regime_inverter_counterfactual_raw_contribution double precision,
  ADD COLUMN IF NOT EXISTS regime_inverter_counterfactual_adjusted_contribution double precision;

CREATE TABLE IF NOT EXISTS public.v6_broad_red_state (
  model_version text PRIMARY KEY,
  model_revision text NOT NULL,
  fit_id text,
  model_artifact_sha256 text,
  feature_schema_version text,
  broad_red_history_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  broad_red_history_count integer NOT NULL DEFAULT 0,
  broad_red_last_resolved_target_ts timestamptz,
  broad_red_last12_wins integer NOT NULL DEFAULT 0,
  broad_red_last12_losses integer NOT NULL DEFAULT 0,
  broad_red_last12_adjusted_net double precision NOT NULL DEFAULT 0,
  broad_red_reliability_ready boolean NOT NULL DEFAULT false,
  broad_red_reliability_veto_active boolean NOT NULL DEFAULT false,
  broad_red_reliability_threshold double precision NOT NULL DEFAULT -2.0,
  broad_red_state_updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT ON public.v6_broad_red_state TO authenticated;
GRANT ALL ON public.v6_broad_red_state TO service_role;
ALTER TABLE public.v6_broad_red_state ENABLE ROW LEVEL SECURITY;
CREATE POLICY "v6_broad_red_state readable by authenticated"
  ON public.v6_broad_red_state FOR SELECT TO authenticated USING (true);