
ALTER TABLE public.predictions
  ADD COLUMN IF NOT EXISTS partial_snapshot_present boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS partial_snapshot_failure_reason text,
  ADD COLUMN IF NOT EXISTS partial_completeness numeric(4,3),
  ADD COLUMN IF NOT EXISTS partial_direction text,
  ADD COLUMN IF NOT EXISTS partial_close_position_pct numeric(4,3),
  ADD COLUMN IF NOT EXISTS partial_range_vs_atr numeric(5,3),
  ADD COLUMN IF NOT EXISTS partial_vwap_event text NOT NULL DEFAULT 'none',
  ADD COLUMN IF NOT EXISTS partial_agreement text NOT NULL DEFAULT 'missing',
  ADD COLUMN IF NOT EXISTS partial_module_bull_pts numeric(4,1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS partial_module_bear_pts numeric(4,1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS partial_veto_active boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS partial_veto_tier text NOT NULL DEFAULT 'none',
  ADD COLUMN IF NOT EXISTS partial_veto_direction text,
  ADD COLUMN IF NOT EXISTS partial_hard_override_fired boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS conflict_downgrade_applied boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS degraded_mode boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS feed_mismatch boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS partial_fetch_source text;

ALTER TABLE public.predictions_archive
  ADD COLUMN IF NOT EXISTS partial_snapshot_present boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS partial_snapshot_failure_reason text,
  ADD COLUMN IF NOT EXISTS partial_completeness numeric(4,3),
  ADD COLUMN IF NOT EXISTS partial_direction text,
  ADD COLUMN IF NOT EXISTS partial_close_position_pct numeric(4,3),
  ADD COLUMN IF NOT EXISTS partial_range_vs_atr numeric(5,3),
  ADD COLUMN IF NOT EXISTS partial_vwap_event text NOT NULL DEFAULT 'none',
  ADD COLUMN IF NOT EXISTS partial_agreement text NOT NULL DEFAULT 'missing',
  ADD COLUMN IF NOT EXISTS partial_module_bull_pts numeric(4,1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS partial_module_bear_pts numeric(4,1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS partial_veto_active boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS partial_veto_tier text NOT NULL DEFAULT 'none',
  ADD COLUMN IF NOT EXISTS partial_veto_direction text,
  ADD COLUMN IF NOT EXISTS partial_hard_override_fired boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS conflict_downgrade_applied boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS degraded_mode boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS feed_mismatch boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS partial_fetch_source text;
