ALTER TABLE public.b4x4_es1_predictions
  ADD COLUMN IF NOT EXISTS dual_adaptive_model_version text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_policy_version text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_implementation_revision text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_feature_schema text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_config_hash text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_activation_id text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_activation_target_ts timestamptz,
  ADD COLUMN IF NOT EXISTS dual_adaptive_input_hash text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_ready boolean,
  ADD COLUMN IF NOT EXISTS dual_adaptive_ready_reason text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_detailed_reason text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_spot_feature_id uuid,
  ADD COLUMN IF NOT EXISTS dual_adaptive_spot_capture_status text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_spot_ready boolean,
  ADD COLUMN IF NOT EXISTS dual_adaptive_spot_ready_reason text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_spot_history_ready boolean,
  ADD COLUMN IF NOT EXISTS dual_adaptive_spot_final_imbalance_10bps double precision,
  ADD COLUMN IF NOT EXISTS dual_adaptive_spot_mean_imbalance_10bps_60s double precision,
  ADD COLUMN IF NOT EXISTS dual_adaptive_spot_final_sign smallint,
  ADD COLUMN IF NOT EXISTS dual_adaptive_spot_mean60_sign smallint,
  ADD COLUMN IF NOT EXISTS dual_adaptive_spot_mode text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_spot_mode_reason text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_spot_direction text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_perp_feature_id uuid,
  ADD COLUMN IF NOT EXISTS dual_adaptive_perp_capture_status text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_perp_ready boolean,
  ADD COLUMN IF NOT EXISTS dual_adaptive_perp_ready_reason text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_perp_history_ready boolean,
  ADD COLUMN IF NOT EXISTS dual_adaptive_perp_final_imbalance_10bps double precision,
  ADD COLUMN IF NOT EXISTS dual_adaptive_perp_mean_imbalance_10bps_60s double precision,
  ADD COLUMN IF NOT EXISTS dual_adaptive_perp_final_sign smallint,
  ADD COLUMN IF NOT EXISTS dual_adaptive_perp_mean60_sign smallint,
  ADD COLUMN IF NOT EXISTS dual_adaptive_perp_mode text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_perp_mode_reason text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_perp_direction text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_venue_agreement boolean,
  ADD COLUMN IF NOT EXISTS dual_adaptive_candidate_direction text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_would_trade boolean,
  ADD COLUMN IF NOT EXISTS dual_adaptive_decision_reason text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_influenced_decision boolean,
  ADD COLUMN IF NOT EXISTS dual_adaptive_webhook_eligible boolean,
  ADD COLUMN IF NOT EXISTS dual_adaptive_webhook_sent_at timestamptz,
  ADD COLUMN IF NOT EXISTS dual_adaptive_result text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_result_score integer,
  ADD COLUMN IF NOT EXISTS dual_adaptive_resolved_at timestamptz,
  ADD COLUMN IF NOT EXISTS dual_adaptive_resolver_version text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_resolution_attempt_count integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS legacy_es1_model_version text;

ALTER TABLE public.b4x4_es1_activation
  ADD COLUMN IF NOT EXISTS dual_adaptive_mode text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_model_version text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_policy_version text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_config_hash text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_approved_at timestamptz,
  ADD COLUMN IF NOT EXISTS dual_adaptive_approval_note text,
  ADD COLUMN IF NOT EXISTS dual_adaptive_activation_target_ts timestamptz,
  ADD COLUMN IF NOT EXISTS dual_adaptive_activation_snapshot jsonb,
  ADD COLUMN IF NOT EXISTS dual_adaptive_created_at timestamptz;

CREATE INDEX IF NOT EXISTS b4x4_es1_predictions_dual_adaptive_idx
  ON public.b4x4_es1_predictions (dual_adaptive_model_version, target_candle_ts DESC);