CREATE TABLE public.v6_predictions (
  prediction_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  target_candle_ts timestamptz NOT NULL,
  prediction_created_at timestamptz NOT NULL DEFAULT now(),
  input_candle_ts timestamptz,
  input_cutoff_ts timestamptz,
  prediction_created_before_target boolean NOT NULL DEFAULT false,
  timing_valid boolean NOT NULL DEFAULT false,
  symbol text NOT NULL DEFAULT 'BTC-USDT',
  timeframe text NOT NULL DEFAULT '15m',
  provider text NOT NULL DEFAULT 'okx',
  model_version text NOT NULL DEFAULT 'V6',
  fit_id text,
  model_artifact_sha256 text,
  feature_schema_version text,
  operational_status text NOT NULL DEFAULT 'OK',
  operational_error text,
  continuity_valid boolean NOT NULL DEFAULT false,
  feature_valid boolean NOT NULL DEFAULT false,
  imputed_feature_count integer NOT NULL DEFAULT 0,
  imputed_features_json jsonb,
  prior_candle_ids_json jsonb,
  input_open double precision,
  input_high double precision,
  input_low double precision,
  input_close double precision,
  input_volume double precision,
  ridge_features_json jsonb,
  gb_features_json jsonb,
  aligned_wick_pressure_4 double precision,
  lower_wick_pct double precision,
  roc_4 double precision,
  range_expansion_vs_avg20 double precision,
  rsi14 double precision,
  cum_vol_delta_to_avg double precision,
  ema21_50_pct double precision,
  dist_to_high20_pct double precision,
  ridge_p_green double precision,
  ridge_percentile double precision,
  gb_p_green double precision,
  gb_percentile double precision,
  broad_score double precision,
  broad_percentile double precision,
  anchor_score double precision,
  anchor_percentile double precision,
  final_score double precision,
  red_threshold double precision,
  green_threshold double precision,
  base_v6_prediction text,
  base_predictions_last8_json jsonb,
  base_green_count_last8 integer,
  saturation_veto_evaluable boolean NOT NULL DEFAULT false,
  saturation_veto_triggered boolean NOT NULL DEFAULT false,
  red_pickup_evaluable boolean NOT NULL DEFAULT false,
  red_pickup_triggered boolean NOT NULL DEFAULT false,
  green_pickup_evaluable boolean NOT NULL DEFAULT false,
  green_pickup_triggered boolean NOT NULL DEFAULT false,
  pickup_conflict boolean NOT NULL DEFAULT false,
  pre_weak_red_veto_prediction text,
  prediction_source text,
  weak_broad_red_veto_evaluable boolean NOT NULL DEFAULT false,
  weak_broad_red_veto_triggered boolean NOT NULL DEFAULT false,
  final_prediction text NOT NULL,
  abstain_status text,
  abstain_reason text,
  canonical_candle_row_id text,
  canonical_open double precision,
  canonical_high double precision,
  canonical_low double precision,
  canonical_close double precision,
  canonical_volume double precision,
  canonical_actual_direction text,
  canonical_ground_truth_valid boolean,
  resolution_timestamp timestamptz,
  base_v6_raw_score double precision,
  base_v6_adjusted_score double precision,
  pre_weak_red_veto_raw_score double precision,
  pre_weak_red_veto_adjusted_score double precision,
  final_raw_score double precision,
  final_adjusted_score double precision,
  saturation_veto_raw_contribution double precision,
  saturation_veto_adjusted_contribution double precision,
  saturation_veto_avoided_loss boolean,
  saturation_veto_sacrificed_win boolean,
  red_pickup_raw_contribution double precision,
  red_pickup_adjusted_contribution double precision,
  green_pickup_raw_contribution double precision,
  green_pickup_adjusted_contribution double precision,
  weak_broad_red_veto_raw_contribution double precision,
  weak_broad_red_veto_adjusted_contribution double precision,
  weak_broad_red_veto_avoided_loss boolean,
  weak_broad_red_veto_sacrificed_win boolean,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT v6_predictions_target_unique UNIQUE (symbol, timeframe, target_candle_ts, model_version)
);

GRANT SELECT ON public.v6_predictions TO authenticated;
GRANT ALL ON public.v6_predictions TO service_role;

ALTER TABLE public.v6_predictions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read V6 tracking"
  ON public.v6_predictions FOR SELECT TO authenticated USING (true);

CREATE INDEX v6_predictions_target_ts_idx ON public.v6_predictions (target_candle_ts DESC);
CREATE INDEX v6_predictions_pending_idx ON public.v6_predictions (resolution_timestamp) WHERE resolution_timestamp IS NULL;

CREATE TRIGGER v6_predictions_set_updated_at
  BEFORE UPDATE ON public.v6_predictions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();