ALTER TABLE public.a96_predictions
  ADD COLUMN IF NOT EXISTS variant text,
  ADD COLUMN IF NOT EXISTS legacy_margin_condition boolean,
  ADD COLUMN IF NOT EXISTS legacy_margin_outside_band boolean,
  ADD COLUMN IF NOT EXISTS body_ratio_max double precision,
  ADD COLUMN IF NOT EXISTS body_ratio_condition boolean,
  ADD COLUMN IF NOT EXISTS body_ratio_veto_fired boolean,
  ADD COLUMN IF NOT EXISTS four_candle_aligned_wick_pressure double precision,
  ADD COLUMN IF NOT EXISTS wick_pressure_max double precision,
  ADD COLUMN IF NOT EXISTS wick_pressure_condition boolean,
  ADD COLUMN IF NOT EXISTS wick_pressure_veto_fired boolean,
  ADD COLUMN IF NOT EXISTS prior_macd_hist double precision,
  ADD COLUMN IF NOT EXISTS prior_atr14 double precision,
  ADD COLUMN IF NOT EXISTS aligned_macd_hist_atr double precision,
  ADD COLUMN IF NOT EXISTS macd_veto_max double precision,
  ADD COLUMN IF NOT EXISTS macd_veto_condition boolean,
  ADD COLUMN IF NOT EXISTS macd_veto_fired boolean,
  ADD COLUMN IF NOT EXISTS r4_feature_history_valid boolean,
  ADD COLUMN IF NOT EXISTS r4_feature_history_error text,
  ADD COLUMN IF NOT EXISTS technical_source_candle_time timestamptz,
  ADD COLUMN IF NOT EXISTS technical_source_candle_row_id text,
  ADD COLUMN IF NOT EXISTS r4_input_candle_times jsonb,
  ADD COLUMN IF NOT EXISTS r4_input_candle_row_ids jsonb,
  ADD COLUMN IF NOT EXISTS r4_feature_snapshot jsonb,
  ADD COLUMN IF NOT EXISTS r3_counterfactual_decision text,
  ADD COLUMN IF NOT EXISTS r3_counterfactual_direction text,
  ADD COLUMN IF NOT EXISTS r3_counterfactual_reason text,
  ADD COLUMN IF NOT EXISTS r3_counterfactual_margin_condition boolean,
  ADD COLUMN IF NOT EXISTS r3_counterfactual_result text,
  ADD COLUMN IF NOT EXISTS r3_counterfactual_result_score integer,
  ADD COLUMN IF NOT EXISTS active_result text,
  ADD COLUMN IF NOT EXISTS active_result_score integer,
  ADD COLUMN IF NOT EXISTS resolution_provider text,
  ADD COLUMN IF NOT EXISTS veto_counterfactual_direction text,
  ADD COLUMN IF NOT EXISTS veto_counterfactual_result text,
  ADD COLUMN IF NOT EXISTS veto_counterfactual_score integer,
  ADD COLUMN IF NOT EXISTS webhook_status text,
  ADD COLUMN IF NOT EXISTS webhook_idempotency_key text,
  ADD COLUMN IF NOT EXISTS webhook_attempt_count integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS webhook_last_attempt_at timestamptz,
  ADD COLUMN IF NOT EXISTS webhook_sent_at timestamptz,
  ADD COLUMN IF NOT EXISTS webhook_last_error text;

CREATE INDEX IF NOT EXISTS a96_predictions_model_version_idx ON public.a96_predictions (model_version);
CREATE UNIQUE INDEX IF NOT EXISTS a96_predictions_webhook_idem_idx ON public.a96_predictions (webhook_idempotency_key) WHERE webhook_idempotency_key IS NOT NULL;