ALTER TABLE public.b4x4_predictions
  ADD COLUMN IF NOT EXISTS calibration_promotion_version text,
  ADD COLUMN IF NOT EXISTS calibration_promotion_history_pool text,
  ADD COLUMN IF NOT EXISTS calibration_promotion_history_window integer,
  ADD COLUMN IF NOT EXISTS calibration_promotion_history_count integer,
  ADD COLUMN IF NOT EXISTS calibration_promotion_history_ready boolean,
  ADD COLUMN IF NOT EXISTS calibration_promotion_raw_direction text,
  ADD COLUMN IF NOT EXISTS calibration_promotion_history_start_ts timestamptz,
  ADD COLUMN IF NOT EXISTS calibration_promotion_history_end_ts timestamptz,
  ADD COLUMN IF NOT EXISTS calibration_promotion_history_as_of_ts timestamptz,
  ADD COLUMN IF NOT EXISTS calibration_promotion_history_wins integer,
  ADD COLUMN IF NOT EXISTS calibration_promotion_history_losses integer,
  ADD COLUMN IF NOT EXISTS calibration_promotion_expected_wins double precision,
  ADD COLUMN IF NOT EXISTS calibration_promotion_observed_win_rate double precision,
  ADD COLUMN IF NOT EXISTS calibration_promotion_expected_win_rate double precision,
  ADD COLUMN IF NOT EXISTS calibration_promotion_variance double precision,
  ADD COLUMN IF NOT EXISTS calibration_promotion_standard_deviation double precision,
  ADD COLUMN IF NOT EXISTS calibration_promotion_residual_wins double precision,
  ADD COLUMN IF NOT EXISTS calibration_promotion_z_score double precision,
  ADD COLUMN IF NOT EXISTS calibration_promotion_min_p_correct double precision,
  ADD COLUMN IF NOT EXISTS calibration_promotion_min_z_score double precision,
  ADD COLUMN IF NOT EXISTS calibration_promotion_history_ids_hash text,
  ADD COLUMN IF NOT EXISTS calibration_promotion_eligibility_reason text,
  ADD COLUMN IF NOT EXISTS calibration_promotion_condition_met boolean,
  ADD COLUMN IF NOT EXISTS calibration_promotion_candidate_before_brake boolean,
  ADD COLUMN IF NOT EXISTS calibration_promotion_brake_vetoed boolean,
  ADD COLUMN IF NOT EXISTS calibration_promotion_published boolean,
  ADD COLUMN IF NOT EXISTS post_calibration_candidate boolean;