ALTER TABLE public.v6_predictions
  ADD COLUMN IF NOT EXISTS pre_structure_prediction text,
  ADD COLUMN IF NOT EXISTS pre_structure_source text,
  ADD COLUMN IF NOT EXISTS structure_confirmation_evaluable boolean,
  ADD COLUMN IF NOT EXISTS structure_rejection_evaluable boolean,
  ADD COLUMN IF NOT EXISTS structure_rejection_pass boolean,
  ADD COLUMN IF NOT EXISTS structure_rejection_lower_wick_value double precision,
  ADD COLUMN IF NOT EXISTS structure_rejection_lower_wick_threshold double precision,
  ADD COLUMN IF NOT EXISTS structure_rejection_aligned_wick_value double precision,
  ADD COLUMN IF NOT EXISTS structure_rejection_aligned_wick_threshold double precision,
  ADD COLUMN IF NOT EXISTS structure_expansion_evaluable boolean,
  ADD COLUMN IF NOT EXISTS structure_expansion_pass boolean,
  ADD COLUMN IF NOT EXISTS structure_expansion_range_value double precision,
  ADD COLUMN IF NOT EXISTS structure_expansion_range_threshold double precision,
  ADD COLUMN IF NOT EXISTS structure_expansion_efficiency_value double precision,
  ADD COLUMN IF NOT EXISTS structure_expansion_efficiency_threshold double precision,
  ADD COLUMN IF NOT EXISTS structure_confirmation_pass boolean,
  ADD COLUMN IF NOT EXISTS structure_confirmation_triggered boolean,
  ADD COLUMN IF NOT EXISTS structure_confirmation_reason text,
  ADD COLUMN IF NOT EXISTS prediction_after_structure_confirmation text,
  ADD COLUMN IF NOT EXISTS prediction_source_after_structure_confirmation text,
  ADD COLUMN IF NOT EXISTS path_efficiency_4 double precision,
  ADD COLUMN IF NOT EXISTS structure_underlying_prediction text,
  ADD COLUMN IF NOT EXISTS structure_underlying_actual_direction text,
  ADD COLUMN IF NOT EXISTS structure_underlying_raw_score double precision,
  ADD COLUMN IF NOT EXISTS structure_underlying_adjusted_score double precision,
  ADD COLUMN IF NOT EXISTS structure_confirmation_raw_contribution double precision,
  ADD COLUMN IF NOT EXISTS structure_confirmation_adjusted_contribution double precision;