ALTER TABLE public.model7_td1_rc_shadow
  ADD COLUMN IF NOT EXISTS td3_policy_version text,
  ADD COLUMN IF NOT EXISTS td3_activation_ts timestamptz,
  ADD COLUMN IF NOT EXISTS td3_source_td1_row_id uuid,
  ADD COLUMN IF NOT EXISTS td3_source_td1_policy_version text,
  ADD COLUMN IF NOT EXISTS td3_source_td1_fit_id text,
  ADD COLUMN IF NOT EXISTS td3_source_td1_artifact_sha256 text,
  ADD COLUMN IF NOT EXISTS td3_pre_veto_decision text,
  ADD COLUMN IF NOT EXISTS td3_pre_veto_would_trade boolean,
  ADD COLUMN IF NOT EXISTS td3_pre_veto_skip_reason text,
  ADD COLUMN IF NOT EXISTS td3_toxic_drift_evaluable boolean,
  ADD COLUMN IF NOT EXISTS td3_current_directional_confidence double precision,
  ADD COLUMN IF NOT EXISTS td3_current_directional_confidence_threshold double precision,
  ADD COLUMN IF NOT EXISTS td3_confidence_condition boolean,
  ADD COLUMN IF NOT EXISTS td3_opposing_drift_4 double precision,
  ADD COLUMN IF NOT EXISTS td3_opposing_drift_4_threshold double precision,
  ADD COLUMN IF NOT EXISTS td3_opposing_drift_condition boolean,
  ADD COLUMN IF NOT EXISTS td3_same_direction_run_length double precision,
  ADD COLUMN IF NOT EXISTS td3_same_direction_run_length_threshold double precision,
  ADD COLUMN IF NOT EXISTS td3_run_length_condition boolean,
  ADD COLUMN IF NOT EXISTS td3_toxic_drift_condition boolean,
  ADD COLUMN IF NOT EXISTS td3_toxic_drift_veto_fired boolean,
  ADD COLUMN IF NOT EXISTS td3_toxic_drift_reason text,
  ADD COLUMN IF NOT EXISTS td3_final_decision text,
  ADD COLUMN IF NOT EXISTS td3_would_trade boolean,
  ADD COLUMN IF NOT EXISTS td3_skip_reason text,
  ADD COLUMN IF NOT EXISTS td3_result text,
  ADD COLUMN IF NOT EXISTS td3_raw_score numeric,
  ADD COLUMN IF NOT EXISTS td3_underlying_td1_decision text,
  ADD COLUMN IF NOT EXISTS td3_underlying_td1_result text,
  ADD COLUMN IF NOT EXISTS td3_underlying_td1_score numeric,
  ADD COLUMN IF NOT EXISTS td3_toxic_drift_veto_value numeric,
  ADD COLUMN IF NOT EXISTS td3_feature_cutoff_ts timestamptz,
  ADD COLUMN IF NOT EXISTS td3_latest_source_candle_ts timestamptz,
  ADD COLUMN IF NOT EXISTS td3_timing_status text,
  ADD COLUMN IF NOT EXISTS td3_leakage_check_passed boolean,
  ADD COLUMN IF NOT EXISTS td3_run_mode text;