// Generated by scripts/build-v12-edge.mjs. Do not edit directly.
import { createHash, createHmac } from "node:crypto";
//#region src/lib/v11/config.ts
var V11_MODEL_VERSION = "v11-original-confidence-rank80-4";
var V11_CANDIDATE_VERSION = "t45-r2-context69-norm-38-r1";
var V11_FEATURE_SCHEMA = "CONTEXT69_NORM_38";
var V11_SOLVER = "ts-lbfgs-certified";
var V11_SCALER = "RobustScaler(10,90)";
var V11_PUBLICATION_MODE = "SHADOW_ONLY";
var V11_POLICY_VERSION = "v11-shadow-r1";
/** Original V1 identity that this stream reads (never writes). */
var V1_MODEL_VERSION = "lite-a-floor4-top10-r1";
/** The 28 T45 PriceFlow inputs, in frozen order, prefixed `feature_`. */
var V11_T45_BASE_ORDER = [
	"t45_ret_5s_bps",
	"t45_ret_15s_bps",
	"t45_ret_30s_bps",
	"t45_ret_45s_bps",
	"t45_last15_ret_bps",
	"t45_last30_ret_bps",
	"t45_return_accel_15_45_bps",
	"t45_range_15s_bps",
	"t45_range_30s_bps",
	"t45_range_45s_bps",
	"t45_body_range_45s",
	"t45_close_location_45s",
	"t45_path_efficiency_45s",
	"t45_realized_vol_45s_bps",
	"t45_log_price_slope_bps_per_s",
	"t45_return_sign_persistence",
	"t45_return_sign_changes",
	"t45_close_vwap_gap_bps",
	"t45_path_direction_consistency",
	"t45_quote_flow_5s",
	"t45_quote_flow_15s",
	"t45_quote_flow_30s",
	"t45_quote_flow_45s",
	"t45_quote_volume_last15_share",
	"t45_trade_count_last15_share",
	"t45_price_flow_alignment",
	"t45_log_quote_volume_45s",
	"t45_log_trade_count_45s"
];
/**
* CONTEXT69 context block: the full 60 minus every name containing
* `_w001_`, `_w002_`, `_w003_`, minus exactly `cm_flow1` (not `cm_flow15`).
* 60 - 18 - 1 = 41.
*/
var V11_CTX_BASE_ORDER = [
	"anchor_t0_basis_bps",
	"anchor_t5_basis_bps",
	"binance_spot_t5_w001_return_bps",
	"binance_spot_t5_w001_flow_imbalance",
	"log1p_binance_spot_t5_w001_quote_volume",
	"binance_spot_t5_w002_return_bps",
	"binance_spot_t5_w002_flow_imbalance",
	"log1p_binance_spot_t5_w002_quote_volume",
	"binance_spot_t5_w003_return_bps",
	"binance_spot_t5_w003_flow_imbalance",
	"log1p_binance_spot_t5_w003_quote_volume",
	"binance_spot_t5_w005_return_bps",
	"binance_spot_t5_w005_flow_imbalance",
	"log1p_binance_spot_t5_w005_quote_volume",
	"binance_spot_t5_w005_range_bps",
	"binance_spot_t5_w005_price_flow_alignment",
	"binance_spot_t0_w060_return_bps",
	"binance_spot_t0_w060_flow_imbalance",
	"binance_spot_t0_w900_return_bps",
	"binance_spot_t0_w900_flow_imbalance",
	"binance_um_t5_w001_return_bps",
	"binance_um_t5_w001_flow_imbalance",
	"log1p_binance_um_t5_w001_quote_volume",
	"binance_um_t5_w002_return_bps",
	"binance_um_t5_w002_flow_imbalance",
	"log1p_binance_um_t5_w002_quote_volume",
	"binance_um_t5_w003_return_bps",
	"binance_um_t5_w003_flow_imbalance",
	"log1p_binance_um_t5_w003_quote_volume",
	"binance_um_t5_w005_return_bps",
	"binance_um_t5_w005_flow_imbalance",
	"log1p_binance_um_t5_w005_quote_volume",
	"binance_um_t5_w005_range_bps",
	"binance_um_t5_w005_price_flow_alignment",
	"binance_um_t0_w060_return_bps",
	"binance_um_t0_w060_flow_imbalance",
	"binance_um_t0_w900_return_bps",
	"binance_um_t0_w900_flow_imbalance",
	"binance_cross_t5_flow_agreement_5s",
	"binance_cross_t5_flow_gap_5s",
	"binance_cross_t5_return_agreement_5s",
	"binance_cross_t5_return_gap_5s",
	"utc_time_sin",
	"utc_time_cos",
	"utc_dow_sin",
	"utc_dow_cos",
	"usdc_anchor_t0_basis_bps",
	"usdc_anchor_t5_basis_bps",
	"quote_premium_bps",
	"index_anchor_t0_basis_bps",
	"index_anchor_t5_basis_bps",
	"index_spot_basis_bps",
	"cm_ret1",
	"cm_ret15",
	"cm_flow1",
	"cm_flow15",
	"cm_basis",
	"cm_basis_change15",
	"cm_flow_excess15",
	"cm_log_volume15"
].filter((n) => !n.includes("_w001_") && !n.includes("_w002_") && !n.includes("_w003_") && n !== "cm_flow1");
/** The 10 normalized base fields (prefixed names as they appear in the row). */
var V11_NORM_BASE_FIELDS = [
	"feature_t45_ret_45s_bps",
	"feature_t45_ret_15s_bps",
	"feature_t45_last15_ret_bps",
	"feature_t45_range_45s_bps",
	"feature_t45_realized_vol_45s_bps",
	"ctx_index_anchor_t0_basis_bps",
	"ctx_index_anchor_t5_basis_bps",
	"ctx_binance_spot_t5_w005_return_bps",
	"ctx_binance_um_t0_w900_return_bps",
	"ctx_cm_ret15"
];
var V11_NORM_DISPLACEMENT = "norm_approx_index_displacement45";
/** Frozen 80-input order: 28 feature_ + 41 ctx_ + 11 norm_. */
var V11_FEATURE_ORDER = [
	...V11_T45_BASE_ORDER.map((n) => `feature_${n}`),
	...V11_CTX_BASE_ORDER.map((n) => `ctx_${n}`),
	...V11_NORM_BASE_FIELDS.map((n) => `norm_${n}`),
	V11_NORM_DISPLACEMENT
];
var V11_CONFIG_CANONICAL = JSON.stringify({
	model_version: V11_MODEL_VERSION,
	candidate_version: V11_CANDIDATE_VERSION,
	feature_schema: V11_FEATURE_SCHEMA,
	feature_order: V11_FEATURE_ORDER,
	scaler: {
		kind: V11_SCALER,
		q_low: .1,
		q_high: .9
	},
	fit: {
		c: .003,
		tol: 1e-4,
		max_iter: 5e3,
		train_days: 90,
		min_train_rows: 2688,
		solver: V11_SOLVER,
		weighting: "utc-day-balanced-mean-1",
		cadence: "daily-utc-midnight"
	},
	vol: {
		source: `ctx_binance_spot_t0_w900_return_bps`,
		window: 96,
		min_finite: 24,
		clip: 200,
		floor_bps: 5,
		includes_current_row: true
	},
	rank: {
		window: 768,
		min_history: 192,
		ties: "midpoint",
		availability_window: 768,
		availability_min: 192,
		gate: "clip(1 - 0.38/availability, 0, 1)",
		fallback_min_rank: .8
	},
	strategy: {
		stake_fraction_of_boise_day_opening_principal: .04,
		one_bet_per_interval: true,
		v1_priority_at_t5: true,
		fallback_at_t45: true
	},
	publication_mode: V11_PUBLICATION_MODE,
	policy_version: V11_POLICY_VERSION
});
/** Stable 64-bit FNV-style digest used to bind heads to their configuration. */
function v11Digest(s) {
	let h1 = 2166136261;
	let h2 = 16777619;
	for (let i = 0; i < s.length; i++) {
		h1 = Math.imul(h1 ^ s.charCodeAt(i), 16777619) >>> 0;
		h2 = Math.imul(h2 + s.charCodeAt(i) + 1, 2246822519) >>> 0;
	}
	return `${h1.toString(16).padStart(8, "0")}${h2.toString(16).padStart(8, "0")}`;
}
v11Digest(V11_FEATURE_ORDER.join(","));
v11Digest(V11_CONFIG_CANONICAL);
//#endregion
//#region src/lib/v11/store.server.ts
/**
* Immutable read of the ORIGINAL V1 leg, including its send-claim state.
* Throws on a DB failure — a failed read is never reported as "no V1 row".
*/
async function readV1Snapshot(sb, targetTs) {
	const { data, error } = await sb.from("c85_targets").select("ticker, status, run_mode, final_side, features, gate_reasons, webhook_status, webhook_dedupe_key, publication_offset_ms, last_receipt_ns").eq("model_version", V1_MODEL_VERSION).eq("target_open_utc", targetTs).maybeSingle();
	if (error) throw error;
	if (!data) return {
		committed: false,
		status: null,
		runMode: null,
		inputValid: false,
		finalSide: null,
		reason: null,
		ordinaryFloorOpen: null,
		sendClaim: "none",
		publicationOffsetMs: null,
		lastReceiptNs: null
	};
	const features = data.features ?? {};
	const liteA = features["lite_a"] ?? {};
	const floor = features["daily_floor"] ?? {};
	const claim = await readV1SendClaim(sb, data.ticker ?? "", targetTs, data.webhook_status ?? null, data.webhook_dedupe_key ?? null);
	const floorRaw = floor["ordinary_floor_allows"];
	return {
		committed: true,
		status: data.status ?? null,
		runMode: data.run_mode ?? null,
		inputValid: features["input_valid"] === true,
		finalSide: data.final_side === null || data.final_side === void 0 ? null : Number(data.final_side),
		reason: liteA["reason"] ?? null,
		ordinaryFloorOpen: floorRaw === void 0 || floorRaw === null ? null : floorRaw === true,
		sendClaim: claim,
		publicationOffsetMs: data.publication_offset_ms === null || data.publication_offset_ms === void 0 ? null : Number(data.publication_offset_ms),
		lastReceiptNs: data.last_receipt_ns === null || data.last_receipt_ns === void 0 ? null : String(data.last_receipt_ns)
	};
}
/**
* Cross-leg exclusion. A different v11 outbox key does NOT guarantee
* exclusivity, so the shared canonical V1 claim is consulted directly: any
* claim row, any non-null webhook status, or a read failure blocks fallback.
*/
async function readV1SendClaim(sb, ticker, targetTs, webhookStatus, dedupeKey) {
	if (webhookStatus) {
		const s = webhookStatus.toUpperCase();
		if (s === "SENT" || s === "DELIVERED") return "sent";
		if (s === "PENDING" || s === "CLAIMED" || s === "IN_FLIGHT") return "claimed";
		return "failed";
	}
	const key = dedupeKey ?? `lite-a-floor4-top10-r1:${ticker}:${new Date(targetTs).toISOString()}`;
	const { data, error } = await sb.from("c85_outbox").select("dedupe_key, state").eq("dedupe_key", key).limit(1);
	if (error) return "unknown";
	const rows = data ?? [];
	if (rows.length === 0) return "none";
	const s = (rows[0].state ?? "").toUpperCase();
	if (s === "SENT" || s === "DELIVERED") return "sent";
	if (s === "FAILED" || s === "ERROR" || s === "EXPIRED") return "failed";
	return "claimed";
}
//#endregion
//#region src/lib/v11/features.ts
function num(v) {
	if (typeof v === "number") return v;
	if (typeof v === "string" && v.trim() !== "") return Number(v);
	return NaN;
}
function clip(v, lo, hi) {
	return v < lo ? lo : v > hi ? hi : v;
}
/**
* Volatility scaler: RMS of `ctx_binance_spot_t0_w900_return_bps` clipped to
* ±200, over the last 96 official opportunity rows INCLUDING the current row's
* pre-open return. `history` must be the chronological official-opportunity
* clock ending with the PREVIOUS row; `current` is this row's value.
* Needs >= 24 finite samples; floored at 5 bps.
*/
function computeV11Vol(history, current) {
	const finite = [...history.slice(-95), current ?? NaN].slice(-96).map((v) => v === null || v === void 0 ? NaN : num(v)).filter((v) => Number.isFinite(v)).map((v) => clip(v, -200, 200));
	if (finite.length < 24) return {
		vol: null,
		finiteCount: finite.length,
		ready: false
	};
	const rms = Math.sqrt(finite.reduce((a, v) => a + v * v, 0) / finite.length);
	const vol = Math.max(rms, 5);
	if (!Number.isFinite(vol)) return {
		vol: null,
		finiteCount: finite.length,
		ready: false
	};
	return {
		vol,
		finiteCount: finite.length,
		ready: true
	};
}
//#endregion
//#region src/lib/v12/contract.ts
/** Frozen V1.2 request. This module cannot place or dispatch an order. */
var V12_VERSION = "v12-original-u-4-5-10-r1";
var ROUTES = {
	V1: {
		model: "v12-v1-r1",
		fraction: .04,
		percent: 4,
		execution: "maker_then_taker",
		endpoint: "v12-v1"
	},
	T45R2: {
		model: "v12-t45r2-r1",
		fraction: .05,
		percent: 5,
		execution: "taker_only",
		endpoint: "v12-t45r2"
	},
	U: {
		model: "v12-original-u-r1",
		fraction: .1,
		percent: 10,
		execution: "maker_then_taker",
		endpoint: "v12-u"
	}
};
/**
* Rolling compatibility only. A V1/U sender still on the wire value
* `maker_only` is accepted and normalized to the current policy; every other
* substitution — including a taker policy on a maker-first route, or any alias
* at all on T45R2 — remains a ROUTE_POLICY_MISMATCH.
*/
var LEGACY_EXECUTION_ALIASES = {
	V1: ["maker_only"],
	T45R2: [],
	U: ["maker_only"]
};
function normalizeExecutionPolicy(route, value) {
	const locked = ROUTES[route]?.execution;
	if (!locked) return null;
	if (value === locked) return locked;
	return typeof value === "string" && LEGACY_EXECUTION_ALIASES[route].includes(value) ? locked : null;
}
var U_CHECKPOINTS = [
	120,
	180,
	300,
	480,
	600,
	720
];
function boiseDay(now) {
	if (!Number.isFinite(now.getTime())) throw new Error("INVALID_TIME");
	const parts = new Intl.DateTimeFormat("en-US", {
		timeZone: "America/Boise",
		year: "numeric",
		month: "2-digit",
		day: "2-digit"
	}).formatToParts(now);
	const get = (key) => parts.find((p) => p.type === key).value;
	return `${get("year")}-${get("month")}-${get("day")}`;
}
/** Route-independent key: separate identities never authorize duplicate exposure. */
function intervalKey(ticker, open) {
	const n = Date.parse(open);
	if (!/^KXBTC15M-[A-Z0-9-]+$/.test(ticker) || !Number.isFinite(n) || n % 9e5 !== 0) throw new Error("INVALID_MARKET_INTERVAL");
	return `v12:${ticker}:${new Date(n).toISOString()}`;
}
function uEligible(v1, t45, anyPriorClaim) {
	return v1.inputValid === true && v1.reason === "CONFIDENCE_ABSTAIN" && v1.ordinaryFloorAllows === true && v1.finalSide === 0 && t45.finalized === true && t45.finalSide === 0 && !anyPriorClaim;
}
function validateSignal(p, route, nowMs) {
	const r = ROUTES[route];
	const execution = normalizeExecutionPolicy(route, p.execution_policy);
	if (p.model_version !== r.model || p.combined_model_version !== "v12-original-u-4-5-10-r1" || p.leg !== route || execution === null || p.stake_fraction_of_boise_day_opening_principal !== r.fraction) throw new Error("ROUTE_POLICY_MISMATCH");
	if (p.mode !== "shadow" || !["YES", "NO"].includes(p.prediction)) throw new Error("INVALID_SHADOW_SIGNAL");
	const open = Date.parse(p.candle_starts_at), decision = Date.parse(p.decision_at), sent = Date.parse(p.sent_at);
	if (![
		open,
		decision,
		sent,
		nowMs
	].every(Number.isFinite) || decision < open || sent < decision || sent > nowMs + 1e3 || nowMs - sent > 5e3 || nowMs - decision > 1e4 || nowMs >= open + 9e5) throw new Error("STALE_SIGNAL");
	if (route === "U") {
		if (!U_CHECKPOINTS.includes(p.checkpoint_seconds) || decision < open + p.checkpoint_seconds * 1e3 || decision > open + p.checkpoint_seconds * 1e3 + 5e3) throw new Error("U_CHECKPOINT_MISMATCH");
		if (!p.v11_eligibility || !uEligible(p.v11_eligibility.v1, p.v11_eligibility.t45, p.v11_eligibility.anyPriorClaim)) throw new Error("U_NOT_ELIGIBLE");
		if (!Number.isFinite(p.limit_all_in) || p.limit_all_in <= 0 || p.limit_all_in >= 1 || !["L", "R"].includes(p.u_source)) throw new Error("U_LIMIT_MISSING");
	} else if (decision - open > 6e4 || route === "T45R2" && decision - open < 45e3) throw new Error("EARLY_ROUTE_WINDOW");
	const key = intervalKey(p.market, p.candle_starts_at);
	if (p.interval_key !== key) throw new Error("INTERVAL_KEY_MISMATCH");
	return {
		key,
		route,
		policy: r,
		execution,
		legacyExecutionAlias: p.execution_policy !== execution,
		day: boiseDay(new Date(nowMs))
	};
}
//#endregion
//#region src/lib/v12/context.server.ts
/**
* Minimal early-route reader for the latency-critical V1/T45R2 dispatch.
*
* It resolves exactly the same identity, committed state, input validity, run
* mode and signed T45 provenance that `readV12Context` applies to those two
* legs, using two parallel reads. It deliberately omits the U feature row, the
* 96-row volatility history and the U-only prior-claim read: none of those are
* inputs to a V1 or T45R2 decision. U always goes through `readV12Context`, and
* the full reader remains the authoritative revalidation path.
*/
async function readV12EarlyContext(sb, open) {
	const [target, fallback] = await Promise.all([sb.from("c85_targets").select("ticker,target_open_utc,run_mode,final_side,probability_yes,publication_offset_ms,features").eq("model_version", "lite-a-floor4-top10-r1").eq("target_open_utc", open).maybeSingle(), sb.from("v11_decisions").select("ticker,target_ts,leg,side,reason,probability,decision_offset_ms,run_mode,evidence,within_publication_ceiling,created_at").eq("target_ts", open).maybeSingle()]);
	for (const result of [target, fallback]) if (result.error) throw result.error;
	const v1 = target.data, t45 = fallback.data;
	if (!v1 || v1.run_mode !== "LIVE") return {
		ready: false,
		reason: "V1_NOT_COMMITTED_LIVE"
	};
	return {
		ready: true,
		ticker: v1.ticker,
		open: new Date(open).toISOString(),
		v1,
		t45: t45 && t45.ticker === v1.ticker && t45.within_publication_ceiling === true ? t45 : null
	};
}
async function readV12Context(sb, open) {
	const [snapshot, target, fallback, early, history] = await Promise.all([
		readV1Snapshot(sb, open),
		sb.from("c85_targets").select("ticker,target_open_utc,run_mode,final_side,probability_yes,publication_offset_ms,features").eq("model_version", "lite-a-floor4-top10-r1").eq("target_open_utc", open).maybeSingle(),
		sb.from("v11_decisions").select("ticker,target_ts,leg,side,reason,probability,decision_offset_ms,run_mode,evidence,within_publication_ceiling,created_at").eq("target_ts", open).maybeSingle(),
		sb.from("t45_features").select("spot_complete,t45_quote_flow_45s,t45_quote_flow_15s,t45_close_vwap_gap_bps,t45_path_efficiency_45s,t45_last15_ret_bps,t45_trade_count_last15_share").eq("feature_version", "t45-features-r1").eq("target_ts", open).maybeSingle(),
		sb.from("c85_targets").select("target_open_utc,features").eq("model_version", "lite-a-floor4-top10-r1").lte("target_open_utc", open).order("target_open_utc", { ascending: false }).limit(96)
	]);
	for (const result of [
		target,
		fallback,
		early,
		history
	]) if (result.error) throw result.error;
	const v1 = target.data, t45 = fallback.data;
	if (!v1 || !snapshot.committed || snapshot.runMode !== "LIVE") return {
		ready: false,
		reason: "V1_NOT_COMMITTED_LIVE"
	};
	const eligibility = {
		v1: {
			inputValid: snapshot.inputValid,
			reason: snapshot.reason,
			ordinaryFloorAllows: snapshot.ordinaryFloorOpen === true,
			finalSide: snapshot.finalSide
		},
		t45: {
			finalized: !!t45 && t45.run_mode === "LIVE_SHADOW" && t45.ticker === v1.ticker && t45.evidence?.trigger_signed === true && t45.within_publication_ceiling === true,
			finalSide: t45?.side
		},
		anyPriorClaim: snapshot.sendClaim !== "none"
	};
	const rows = (history.data ?? []).slice().reverse();
	const raw = rows.map((r) => r.features?.direction60?.binance_spot_t0_w900_return_bps ?? null);
	const last = rows.at(-1);
	const vol = last && Date.parse(last.target_open_utc) === Date.parse(open) ? computeV11Vol(raw.slice(0, -1), raw.at(-1)) : { vol: null };
	const e = early.data;
	let features = null;
	if (e?.spot_complete === true && vol.vol !== null) {
		const fields = [
			"quote_flow_45s",
			"quote_flow_15s",
			"close_vwap_gap_bps",
			"path_efficiency_45s",
			"trade_count_last15_share"
		];
		const values = fields.map((k) => e["t45_" + k]);
		if (values.every((v) => typeof v === "number" && Number.isFinite(v)) && typeof e.t45_last15_ret_bps === "number" && Number.isFinite(e.t45_last15_ret_bps)) {
			features = Object.fromEntries(fields.map((k, i) => ["feature_t45_" + k, values[i]]));
			features.norm_feature_t45_last15_ret_bps = Math.max(-10, Math.min(10, e.t45_last15_ret_bps / vol.vol));
		}
	}
	return {
		ready: true,
		ticker: v1.ticker,
		open: new Date(open).toISOString(),
		v1,
		t45,
		eligibility,
		early: features,
		u_eligible: uEligible(eligibility.v1, eligibility.t45, eligibility.anyPriorClaim)
	};
}
//#endregion
//#region src/lib/v12/receiver-destination.ts
var V12_RECEIVER_BASE = "https://ruxndqfjfdbtdbkheuge.supabase.co/functions/v1/";
var V12_SECRET_ENDPOINTS = ["https://ruxndqfjfdbtdbkheuge.supabase.co/functions/v1/place-trade", "https://ruxndqfjfdbtdbkheuge.supabase.co/functions/v1/place-trade?forceFunctionRegion=us-west-1"];
function isAuthorizedBettingEndpoint(value) {
	if (typeof value !== "string") return false;
	try {
		const url = new URL(value), expected = new URL("https://ruxndqfjfdbtdbkheuge.supabase.co/functions/v1/place-trade");
		if (url.origin !== expected.origin || url.pathname !== expected.pathname || url.username || url.password || url.hash) return false;
		const params = [...url.searchParams];
		return params.length === 0 || params.length === 1 && params[0][0] === "forceFunctionRegion" && params[0][1] === "us-west-1";
	} catch {
		return false;
	}
}
//#endregion
//#region src/lib/v12/shadow.server.ts
async function publishV12Shadow(sb, payload, now = Date.now()) {
	const started = Date.now();
	const route = payload.leg;
	if (!Object.hasOwn(ROUTES, route)) throw new Error("UNKNOWN_ROUTE");
	validateSignal(payload, route, now);
	const destination = V12_RECEIVER_BASE;
	const { data, error } = await sb.from("webhook_endpoints").select("secret,url,is_active").in("url", V12_SECRET_ENDPOINTS);
	if (error) throw error;
	const endpoints = (data ?? []).filter((e) => isAuthorizedBettingEndpoint(e.url));
	if (endpoints.length !== 1 || !endpoints[0].secret) throw new Error("SINGLE_BETTING_SECRET_UNAVAILABLE");
	const raw = JSON.stringify(payload), signature = createHmac("sha256", endpoints[0].secret).update(raw).digest("hex");
	const eventKey = payload.interval_key + ":" + route;
	const secretRead = Date.now();
	const { error: claimError } = await sb.from("v12_prediction_events").insert({
		event_key: eventKey,
		request_hash: createHash("sha256").update(raw).digest("hex"),
		route,
		model_version: payload.model_version,
		market: payload.market,
		candle_starts_at: payload.candle_starts_at,
		decision_at: payload.decision_at,
		prediction: payload.prediction,
		checkpoint_seconds: payload.checkpoint_seconds ?? null,
		u_source: payload.u_source ?? null
	});
	if (claimError) throw new Error(claimError.code === "23505" ? "DELIVERY_ALREADY_ATTEMPTED" : "DELIVERY_JOURNAL_UNAVAILABLE");
	const journalMs = Date.now() - secretRead, httpStarted = Date.now();
	try {
		const response = await fetch(destination + ROUTES[route].endpoint, {
			method: "POST",
			body: raw,
			redirect: "error",
			signal: AbortSignal.timeout(2500),
			headers: {
				"content-type": "application/json",
				"x-btc15m-signature": "sha256=" + signature,
				"x-v12-event-id": eventKey,
				"x-v12-model": ROUTES[route].model,
				"x-v12-leg": route
			}
		});
		if (!response.ok) throw new Error("SHADOW_RECEIVER_HTTP_" + response.status);
		const result = await response.json();
		if (typeof result.execution_enabled !== "boolean" || !["shadow", "live"].includes(result.mode)) throw new Error("SHADOW_RECEIVER_CONTRACT_MISMATCH");
		const timings = {
			secret_read_ms: secretRead - started,
			journal_ms: journalMs,
			http_ms: Date.now() - httpStarted,
			dispatch_at_ms: httpStarted
		};
		const { error } = await sb.from("v12_prediction_events").update({
			delivery_status: "ACKNOWLEDGED",
			acknowledged_at: (/* @__PURE__ */ new Date()).toISOString(),
			receiver_status: typeof result.status === "string" ? result.status : null,
			receiver_receipt_id: typeof result.id === "string" ? result.id : null
		}).eq("event_key", eventKey);
		return {
			...result,
			event_key: eventKey,
			receipt_journaled: !error,
			timings
		};
	} catch (e) {
		const code = e instanceof Error && /^SHADOW_RECEIVER_[A-Z_0-9]+$/.test(e.message) ? e.message : "DELIVERY_ACK_UNKNOWN";
		await sb.from("v12_prediction_events").update({
			delivery_status: "UNKNOWN",
			error_code: code
		}).eq("event_key", eventKey);
		throw new Error(code);
	}
}
//#endregion
//#region src/lib/v12/runtime.server.ts
var FIELDS = [
	"stage",
	"fit_expires_at",
	"fit_version",
	"last_context_at",
	"last_error",
	"u_eligible",
	"u_block_reason",
	"early_features_ready",
	"quote_received_at",
	"quote_error",
	"index_complete_through",
	"spot_complete_through",
	"perp_complete_through",
	"refresh_status",
	"refresh_error",
	"training_rows",
	"training_latest_at",
	"last_attempt_at",
	"last_attempt_status",
	"last_attempt_checkpoint",
	"early_dispatch_at",
	"early_dispatch_ms",
	"early_dispatch_error",
	"last_dispatch_leg",
	"last_dispatch_at",
	"last_dispatch_decision_to_dispatch_ms",
	"last_dispatch_decision_to_receipt_ms"
];
async function recordRuntime(sb, input) {
	if (!input || typeof input !== "object" || Array.isArray(input) || input.mode !== "shadow" || input.execution_enabled !== false) throw new Error("INVALID_PREDICTOR_STATUS");
	const status = {
		mode: "shadow",
		execution_enabled: false
	};
	for (const key of FIELDS) {
		const value = input[key];
		if (value === null || typeof value === "boolean" || typeof value === "number" && Number.isFinite(value) || typeof value === "string" && value.length <= 160) status[key] = value;
	}
	const probe = input.receiver_probe;
	if (probe && Array.isArray(probe.receivers)) status.receiver_auth = Object.fromEntries([
		"V1",
		"T45R2",
		"U"
	].map((leg) => [leg, probe.receivers.some((r) => r.leg === leg && r.authenticated === true)]));
	const { error } = await sb.from("v12_predictor_runtime").upsert({
		worker_id: "v12-shadow-worker",
		received_at: (/* @__PURE__ */ new Date()).toISOString(),
		status
	});
	if (error) throw new Error("PREDICTOR_STATUS_STORE_UNAVAILABLE");
	return { recorded: true };
}
//#endregion
//#region src/lib/v12/edge-adapter.ts
var ADAPTER_REVISION = "v12-edge-adapter-r4";
var RECEIVERS = V12_RECEIVER_BASE;
var encoder = new TextEncoder();
var EARLY_LEGS = ["V1", "T45R2"];
/**
* Build a V1/T45R2 signal straight from the committed decision the adapter just
* read. Direction, decision time and market all come from the authoritative row
* — the worker cannot assert any of them — so a historical or non-current
* decision can never be dispatched.
*/
function buildEarlySignal(leg, context, open, now) {
	const v1 = context.v1, t45 = context.t45;
	if (!v1 || v1.features?.input_valid !== true) return {
		leg,
		status: "V1_INPUT_INVALID"
	};
	if (leg === "T45R2" && (!t45 || t45.leg !== "T45R2" || t45.run_mode !== "LIVE_SHADOW" || t45.evidence?.trigger_signed !== true)) return {
		leg,
		status: "NOT_COMMITTED"
	};
	const side = leg === "V1" ? v1.final_side : t45?.side;
	const offset = leg === "V1" ? v1.publication_offset_ms : t45?.decision_offset_ms;
	if (![1, -1].includes(side) || typeof offset !== "number") return {
		leg,
		status: "NOT_COMMITTED"
	};
	const decision = open + offset;
	if (now < decision) return {
		leg,
		status: "NOT_COMMITTED"
	};
	if (now - decision > 8e3) return {
		leg,
		status: "DECISION_EXPIRED"
	};
	const r = ROUTES[leg];
	return {
		leg,
		status: "READY",
		decision,
		signal: {
			mode: "shadow",
			model_version: r.model,
			combined_model_version: V12_VERSION,
			leg,
			execution_policy: r.execution,
			stake_fraction_of_boise_day_opening_principal: r.fraction,
			market: context.ticker,
			candle_starts_at: new Date(open).toISOString(),
			decision_at: new Date(decision).toISOString(),
			sent_at: new Date(now).toISOString(),
			interval_key: intervalKey(context.ticker, new Date(open).toISOString()),
			prediction: side === 1 ? "YES" : "NO"
		}
	};
}
async function verifyWorkerSignature(raw, timestamp, signature, secret, now) {
	if (!secret || !timestamp || !/^\d{13}$/.test(timestamp) || !signature || !/^[0-9a-f]{64}$/.test(signature) || Math.abs(now - Number(timestamp)) > 1e4) return false;
	const key = await crypto.subtle.importKey("raw", encoder.encode(secret), {
		name: "HMAC",
		hash: "SHA-256"
	}, false, ["verify"]);
	const bytes = Uint8Array.from(signature.match(/../g), (h) => parseInt(h, 16));
	return crypto.subtle.verify("HMAC", key, bytes, encoder.encode(`${timestamp}.${raw}`));
}
async function probeReceivers(sb, transport, now) {
	const { data, error } = await sb.from("webhook_endpoints").select("secret,url,is_active").in("url", V12_SECRET_ENDPOINTS);
	if (error) throw error;
	const endpoints = (data ?? []).filter((e) => isAuthorizedBettingEndpoint(e.url));
	if (endpoints.length !== 1 || !endpoints[0].secret) throw new Error("SINGLE_BETTING_SECRET_UNAVAILABLE");
	const results = await Promise.all(Object.keys(ROUTES).map(async (leg) => {
		const raw = JSON.stringify({
			mode: "shadow",
			kind: "V12_READINESS_PROBE",
			leg,
			sent_at: new Date(now).toISOString()
		});
		const signature = createHmac("sha256", endpoints[0].secret).update(raw).digest("hex");
		try {
			const response = await transport(RECEIVERS + ROUTES[leg].endpoint, {
				method: "POST",
				body: raw,
				redirect: "error",
				signal: AbortSignal.timeout(2500),
				headers: {
					"content-type": "application/json",
					"x-btc15m-signature": "sha256=" + signature
				}
			});
			const result = await response.json();
			return {
				leg,
				authenticated: response.status === 200 && result.kind === "V12_READINESS_PROBE",
				status: response.status,
				ready_for_activation: result.ready_for_activation === true,
				release_mode: result.mode ?? null,
				checks: result.checks ?? null
			};
		} catch {
			return {
				leg,
				authenticated: false,
				status: null
			};
		}
	}));
	return {
		all_authenticated: results.every((r) => r.authenticated),
		receivers: results,
		records_created: 0
	};
}
function createAdapterHandler(deps) {
	const clock = deps.clock ?? Date.now;
	const reply = (status, body) => Response.json({
		...body,
		adapter_revision: ADAPTER_REVISION,
		mode: "shadow",
		execution_enabled: false
	}, {
		status,
		headers: { "cache-control": "no-store" }
	});
	return async (request) => {
		if (request.method !== "POST") return reply(405, {
			ok: false,
			error: "POST_REQUIRED"
		});
		if (Number(request.headers.get("content-length") || 0) > 32768) return reply(413, {
			ok: false,
			error: "BODY_TOO_LARGE"
		});
		const raw = await request.text();
		if (encoder.encode(raw).length > 32768) return reply(413, {
			ok: false,
			error: "BODY_TOO_LARGE"
		});
		if (!await verifyWorkerSignature(raw, request.headers.get("x-c85-timestamp"), request.headers.get("x-c85-signature"), deps.secret(), clock())) return reply(401, {
			ok: false,
			error: "INVALID_SIGNATURE"
		});
		let p;
		try {
			p = JSON.parse(raw);
		} catch {
			return reply(400, {
				ok: false,
				error: "INVALID_JSON"
			});
		}
		if (!p || typeof p !== "object" || Array.isArray(p)) return reply(400, {
			ok: false,
			error: "INVALID_ENVELOPE"
		});
		const now = clock(), open = Date.parse(p.open);
		if (![
			"context",
			"early_dispatch",
			"publish",
			"probe",
			"heartbeat"
		].includes(p.op) || typeof p.nonce !== "string" || p.nonce.length < 8 || p.nonce.length > 120 || !Number.isFinite(open) || open % 9e5 !== 0 || now < open || now >= open + 9e5) return reply(400, {
			ok: false,
			error: "INVALID_CURRENT_INTERVAL"
		});
		try {
			const sb = deps.client();
			if (p.op !== "context" && p.op !== "early_dispatch") {
				const { error } = await sb.from("c85_request_nonces").insert({
					nonce: p.nonce,
					op: "v12-shadow." + p.op,
					worker_id: "v12-shadow-worker"
				});
				if (error?.code === "23505") return reply(409, {
					ok: false,
					error: "REPLAYED"
				});
				if (error) throw new Error("NONCE_STORE_UNAVAILABLE");
			}
			if (p.op === "probe") return reply(200, {
				ok: true,
				...await probeReceivers(sb, deps.transport ?? fetch, clock())
			});
			if (p.op === "heartbeat") return reply(200, {
				ok: true,
				...await recordRuntime(sb, p.status)
			});
			if (p.op === "early_dispatch") {
				const requested = Array.isArray(p.legs) ? p.legs : EARLY_LEGS;
				const legs = EARLY_LEGS.filter((l) => requested.includes(l));
				if (!legs.length) return reply(400, {
					ok: false,
					error: "NO_EARLY_LEGS"
				});
				const readStarted = clock();
				const early = await (deps.readEarlyContext ?? readV12EarlyContext)(sb, new Date(open).toISOString());
				const contextReadMs = clock() - readStarted;
				if (!early.ready) return reply(200, {
					ok: true,
					context_ready: false,
					reason: early.reason,
					dispatched: [],
					timings: { context_read_ms: contextReadMs }
				});
				const dispatched = [];
				for (const leg of legs) {
					const built = buildEarlySignal(leg, early, open, clock());
					if (built.status !== "READY") {
						dispatched.push({
							leg,
							status: built.status
						});
						continue;
					}
					try {
						validateSignal(built.signal, leg, clock());
						const published = await (deps.publish ?? publishV12Shadow)(sb, built.signal, clock());
						dispatched.push({
							leg,
							status: "DISPATCHED",
							receiver_status: published.status ?? null,
							receiver_mode: published.mode ?? null,
							decision_at: built.signal.decision_at,
							sent_at: built.signal.sent_at,
							decision_to_dispatch_ms: published.timings?.dispatch_at_ms == null ? null : published.timings.dispatch_at_ms - built.decision,
							decision_to_receipt_ms: published.received_at ? Date.parse(published.received_at) - built.decision : null,
							timings: published.timings ?? null
						});
					} catch (e) {
						dispatched.push({
							leg,
							status: "FAILED",
							error: e instanceof Error ? e.message : "DISPATCH_ERROR"
						});
					}
				}
				return reply(200, {
					ok: true,
					context_ready: true,
					ticker: early.ticker,
					dispatched,
					timings: {
						context_read_ms: contextReadMs,
						total_ms: clock() - readStarted
					}
				});
			}
			const context = await (deps.readContext ?? readV12Context)(sb, new Date(open).toISOString());
			if (p.op === "context") return reply(200, {
				ok: true,
				context,
				observed_at: new Date(clock()).toISOString()
			});
			const signal = p.signal;
			if (!context.ready || !signal || signal.market !== context.ticker || Date.parse(signal.candle_starts_at) !== open) throw new Error("CONTEXT_MISMATCH");
			if (signal.leg === "U") {
				if (!context.u_eligible) throw new Error("U_NOT_ELIGIBLE");
				signal.v11_eligibility = context.eligibility;
			} else {
				const v1 = context.v1, t45 = context.t45;
				if (!v1 || v1.features?.input_valid !== true) throw new Error("V1_INPUT_INVALID");
				if (signal.leg !== "V1" && signal.leg !== "T45R2") throw new Error("UNKNOWN_ROUTE");
				const side = signal.leg === "V1" ? v1.final_side : t45?.side;
				if (signal.leg === "T45R2" && (!t45 || t45.leg !== "T45R2" || t45.run_mode !== "LIVE_SHADOW" || t45.evidence?.trigger_signed !== true) || ![1, -1].includes(side) || signal.prediction !== (side === 1 ? "YES" : "NO")) throw new Error("COMMITTED_DIRECTION_MISMATCH");
				const offset = signal.leg === "V1" ? v1.publication_offset_ms : t45?.decision_offset_ms;
				if (typeof offset !== "number" || Math.abs(Date.parse(signal.decision_at) - (open + offset)) > 1) throw new Error("DECISION_TIME_MISMATCH");
			}
			validateSignal(signal, signal.leg, clock());
			const result = await (deps.publish ?? publishV12Shadow)(sb, signal, clock());
			return reply(200, {
				ok: true,
				...result,
				receiver_mode: result.mode,
				receiver_execution_enabled: result.execution_enabled
			});
		} catch (e) {
			return reply(400, {
				ok: false,
				error: e instanceof Error ? e.message : "ADAPTER_ERROR"
			});
		}
	};
}
//#endregion
export { ADAPTER_REVISION, createAdapterHandler, readV12Context, readV12EarlyContext, verifyWorkerSignature };
